-- Seek Daily Verses Seed Data (365 KJV verses across 20 themes)
-- Themes: strength, peace, comfort, praise, wisdom, hope, faith, love, guidance, gratitude,
--         courage, patience, joy, trust, provision, protection, healing, forgiveness, purpose, prayer

INSERT INTO daily_verses (reference, text, theme) VALUES
-- STRENGTH (18 verses)
('Isaiah 40:31', 'But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.', 'strength'),
('Philippians 4:13', 'I can do all things through Christ which strengtheneth me.', 'strength'),
('Psalm 46:1', 'God is our refuge and strength, a very present help in trouble.', 'strength'),
('2 Corinthians 12:9', 'And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness.', 'strength'),
('Deuteronomy 31:6', 'Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.', 'strength'),
('Psalm 73:26', 'My flesh and my heart faileth: but God is the strength of my heart, and my portion for ever.', 'strength'),
('Isaiah 41:10', 'Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.', 'strength'),
('Nehemiah 8:10', 'Then he said unto them, Go your way, eat the fat, and drink the sweet, and send portions unto them for whom nothing is prepared: for this day is holy unto our Lord: neither be ye sorry; for the joy of the LORD is your strength.', 'strength'),
('Psalm 18:32', 'It is God that girdeth me with strength, and maketh my way perfect.', 'strength'),
('Psalm 27:1', 'The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?', 'strength'),
('Psalm 28:7', 'The LORD is my strength and my shield; my heart trusted in him, and I am helped: therefore my heart greatly rejoiceth; and with my song will I praise him.', 'strength'),
('Psalm 29:11', 'The LORD will give strength unto his people; the LORD will bless his people with peace.', 'strength'),
('Psalm 31:24', 'Be of good courage, and he shall strengthen your heart, all ye that hope in the LORD.', 'strength'),
('Psalm 37:39', 'But the salvation of the righteous is of the LORD: he is their strength in the time of trouble.', 'strength'),
('Psalm 68:35', 'O God, thou art terrible out of thy holy places: the God of Israel is he that giveth strength and power unto his people. Blessed be God.', 'strength'),
('Psalm 138:3', 'In the day when I cried thou answeredst me, and strengthenedst me with strength in my soul.', 'strength'),
('Habakkuk 3:19', 'The LORD God is my strength, and he will make my feet like hinds'' feet, and he will make me to walk upon mine high places.', 'strength'),
('Ephesians 6:10', 'Finally, my brethren, be strong in the Lord, and in the power of his might.', 'strength'),

-- PEACE (18 verses)
('John 14:27', 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.', 'peace'),
('Philippians 4:6-7', 'Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.', 'peace'),
('Isaiah 26:3', 'Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.', 'peace'),
('Romans 8:6', 'For to be carnally minded is death; but to be spiritually minded is life and peace.', 'peace'),
('Psalm 4:8', 'I will both lay me down in peace, and sleep: for thou, LORD, only makest me dwell in safety.', 'peace'),
('Colossians 3:15', 'And let the peace of God rule in your hearts, to the which also ye are called in one body; and be ye thankful.', 'peace'),
('Psalm 29:11', 'The LORD will give strength unto his people; the LORD will bless his people with peace.', 'peace'),
('Romans 15:13', 'Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.', 'peace'),
('Matthew 5:9', 'Blessed are the peacemakers: for they shall be called the children of God.', 'peace'),
('Psalm 119:165', 'Great peace have they which love thy law: and nothing shall offend them.', 'peace'),
('Isaiah 9:6', 'For unto us a child is born, unto us a son is given: and the government shall be upon his shoulder: and his name shall be called Wonderful, Counsellor, The mighty God, The everlasting Father, The Prince of Peace.', 'peace'),
('John 16:33', 'These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world.', 'peace'),
('2 Thessalonians 3:16', 'Now the Lord of peace himself give you peace always by all means. The Lord be with you all.', 'peace'),
('Numbers 6:26', 'The LORD lift up his countenance upon thee, and give thee peace.', 'peace'),
('Psalm 34:14', 'Depart from evil, and do good; seek peace, and pursue it.', 'peace'),
('Isaiah 55:12', 'For ye shall go out with joy, and be led forth with peace: the mountains and the hills shall break forth before you into singing, and all the trees of the field shall clap their hands.', 'peace'),
('Romans 5:1', 'Therefore being justified by faith, we have peace with God through our Lord Jesus Christ.', 'peace'),
('Galatians 5:22', 'But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith.', 'peace'),

-- COMFORT (18 verses)
('Psalm 23:4', 'Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.', 'comfort'),
('2 Corinthians 1:3-4', 'Blessed be God, even the Father of our Lord Jesus Christ, the Father of mercies, and the God of all comfort; Who comforteth us in all our tribulation, that we may be able to comfort them which are in any trouble, by the comfort wherewith we ourselves are comforted of God.', 'comfort'),
('Matthew 11:28', 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.', 'comfort'),
('Psalm 34:18', 'The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit.', 'comfort'),
('Isaiah 49:13', 'Sing, O heavens; and be joyful, O earth; and break forth into singing, O mountains: for the LORD hath comforted his people, and will have mercy upon his afflicted.', 'comfort'),
('Psalm 147:3', 'He healeth the broken in heart, and bindeth up their wounds.', 'comfort'),
('Revelation 21:4', 'And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain: for the former things are passed away.', 'comfort'),
('Isaiah 41:13', 'For I the LORD thy God will hold thy right hand, saying unto thee, Fear not; I will help thee.', 'comfort'),
('Psalm 55:22', 'Cast thy burden upon the LORD, and he shall sustain thee: he shall never suffer the righteous to be moved.', 'comfort'),
('Romans 8:28', 'And we know that all things work together for good to them that love God, to them who are the called according to his purpose.', 'comfort'),
('Psalm 94:19', 'In the multitude of my thoughts within me thy comforts delight my soul.', 'comfort'),
('Isaiah 66:13', 'As one whom his mother comforteth, so will I comfort you; and ye shall be comforted in Jerusalem.', 'comfort'),
('Psalm 30:5', 'For his anger endureth but a moment; in his favour is life: weeping may endure for a night, but joy cometh in the morning.', 'comfort'),
('Lamentations 3:22-23', 'It is of the LORD''s mercies that we are not consumed, because his compassions fail not. They are new every morning: great is thy faithfulness.', 'comfort'),
('2 Corinthians 4:17', 'For our light affliction, which is but for a moment, worketh for us a far more exceeding and eternal weight of glory.', 'comfort'),
('Psalm 71:21', 'Thou shalt increase my greatness, and comfort me on every side.', 'comfort'),
('John 14:1', 'Let not your heart be troubled: ye believe in God, believe also in me.', 'comfort'),
('1 Peter 5:7', 'Casting all your care upon him; for he careth for you.', 'comfort'),

-- PRAISE (18 verses)
('Psalm 150:6', 'Let every thing that hath breath praise the LORD. Praise ye the LORD.', 'praise'),
('Psalm 100:4', 'Enter into his gates with thanksgiving, and into his courts with praise: be thankful unto him, and bless his name.', 'praise'),
('Psalm 34:1', 'I will bless the LORD at all times: his praise shall continually be in my mouth.', 'praise'),
('Hebrews 13:15', 'By him therefore let us offer the sacrifice of praise to God continually, that is, the fruit of our lips giving thanks to his name.', 'praise'),
('Psalm 145:3', 'Great is the LORD, and greatly to be praised; and his greatness is unsearchable.', 'praise'),
('Psalm 9:1-2', 'I will praise thee, O LORD, with my whole heart; I will shew forth all thy marvellous works. I will be glad and rejoice in thee: I will sing praise to thy name, O thou most High.', 'praise'),
('Psalm 95:1', 'O come, let us sing unto the LORD: let us make a joyful noise to the rock of our salvation.', 'praise'),
('Psalm 103:1', 'Bless the LORD, O my soul: and all that is within me, bless his holy name.', 'praise'),
('Psalm 113:3', 'From the rising of the sun unto the going down of the same the LORD''s name is to be praised.', 'praise'),
('Psalm 148:13', 'Let them praise the name of the LORD: for his name alone is excellent; his glory is above the earth and heaven.', 'praise'),
('Psalm 96:4', 'For the LORD is great, and greatly to be praised: he is to be feared above all gods.', 'praise'),
('Psalm 63:3', 'Because thy lovingkindness is better than life, my lips shall praise thee.', 'praise'),
('Psalm 71:8', 'Let my mouth be filled with thy praise and with thy honour all the day.', 'praise'),
('Psalm 135:3', 'Praise the LORD; for the LORD is good: sing praises unto his name; for it is pleasant.', 'praise'),
('Psalm 42:11', 'Why art thou cast down, O my soul? and why art thou disquieted within me? hope thou in God: for I shall yet praise him, who is the health of my countenance, and my God.', 'praise'),
('Acts 16:25', 'And at midnight Paul and Silas prayed, and sang praises unto God: and the prisoners heard them.', 'praise'),
('Psalm 150:1', 'Praise ye the LORD. Praise God in his sanctuary: praise him in the firmament of his power.', 'praise'),
('Psalm 146:1-2', 'Praise ye the LORD. Praise the LORD, O my soul. While I live will I praise the LORD: I will sing praises unto my God while I have any being.', 'praise'),

-- WISDOM (18 verses)
('Proverbs 3:5-6', 'Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.', 'wisdom'),
('James 1:5', 'If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.', 'wisdom'),
('Proverbs 4:7', 'Wisdom is the principal thing; therefore get wisdom: and with all thy getting get understanding.', 'wisdom'),
('Psalm 111:10', 'The fear of the LORD is the beginning of wisdom: a good understanding have all they that do his commandments: his praise endureth for ever.', 'wisdom'),
('Proverbs 2:6', 'For the LORD giveth wisdom: out of his mouth cometh knowledge and understanding.', 'wisdom'),
('Colossians 3:16', 'Let the word of Christ dwell in you richly in all wisdom; teaching and admonishing one another in psalms and hymns and spiritual songs, singing with grace in your hearts to the Lord.', 'wisdom'),
('Proverbs 16:16', 'How much better is it to get wisdom than gold! and to get understanding rather to be chosen than silver!', 'wisdom'),
('Ecclesiastes 7:12', 'For wisdom is a defence, and money is a defence: but the excellency of knowledge is, that wisdom giveth life to them that have it.', 'wisdom'),
('Proverbs 9:10', 'The fear of the LORD is the beginning of wisdom: and the knowledge of the holy is understanding.', 'wisdom'),
('Proverbs 1:7', 'The fear of the LORD is the beginning of knowledge: but fools despise wisdom and instruction.', 'wisdom'),
('Proverbs 19:20', 'Hear counsel, and receive instruction, that thou mayest be wise in thy latter end.', 'wisdom'),
('Proverbs 11:2', 'When pride cometh, then cometh shame: but with the lowly is wisdom.', 'wisdom'),
('Proverbs 3:13', 'Happy is the man that findeth wisdom, and the man that getteth understanding.', 'wisdom'),
('James 3:17', 'But the wisdom that is from above is first pure, then peaceable, gentle, and easy to be intreated, full of mercy and good fruits, without partiality, and without hypocrisy.', 'wisdom'),
('Proverbs 24:14', 'So shall the knowledge of wisdom be unto thy soul: when thou hast found it, then there shall be a reward, and thy expectation shall not be cut off.', 'wisdom'),
('Proverbs 12:15', 'The way of a fool is right in his own eyes: but he that hearkeneth unto counsel is wise.', 'wisdom'),
('Psalm 90:12', 'So teach us to number our days, that we may apply our hearts unto wisdom.', 'wisdom'),
('1 Corinthians 1:30', 'But of him are ye in Christ Jesus, who of God is made unto us wisdom, and righteousness, and sanctification, and redemption.', 'wisdom'),

-- HOPE (19 verses)
('Romans 15:13', 'Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.', 'hope'),
('Jeremiah 29:11', 'For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.', 'hope'),
('Romans 8:24-25', 'For we are saved by hope: but hope that is seen is not hope: for what a man seeth, why doth he yet hope for? But if we hope for that we see not, then do we with patience wait for it.', 'hope'),
('Psalm 62:5', 'My soul, wait thou only upon God; for my expectation is from him.', 'hope'),
('Hebrews 6:19', 'Which hope we have as an anchor of the soul, both sure and stedfast, and which entereth into that within the veil.', 'hope'),
('Psalm 39:7', 'And now, Lord, what wait I for? my hope is in thee.', 'hope'),
('Psalm 71:5', 'For thou art my hope, O Lord GOD: thou art my trust from my youth.', 'hope'),
('Romans 5:5', 'And hope maketh not ashamed; because the love of God is shed abroad in our hearts by the Holy Ghost which is given unto us.', 'hope'),
('1 Peter 1:3', 'Blessed be the God and Father of our Lord Jesus Christ, which according to his abundant mercy hath begotten us again unto a lively hope by the resurrection of Jesus Christ from the dead.', 'hope'),
('Psalm 130:5', 'I wait for the LORD, my soul doth wait, and in his word do I hope.', 'hope'),
('Isaiah 40:31', 'But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.', 'hope'),
('Romans 12:12', 'Rejoicing in hope; patient in tribulation; continuing instant in prayer.', 'hope'),
('Psalm 33:18', 'Behold, the eye of the LORD is upon them that fear him, upon them that hope in his mercy.', 'hope'),
('Psalm 42:5', 'Why art thou cast down, O my soul? and why art thou disquieted in me? hope thou in God: for I shall yet praise him for the help of his countenance.', 'hope'),
('Psalm 146:5', 'Happy is he that hath the God of Jacob for his help, whose hope is in the LORD his God.', 'hope'),
('Titus 2:13', 'Looking for that blessed hope, and the glorious appearing of the great God and our Saviour Jesus Christ.', 'hope'),
('Hebrews 11:1', 'Now faith is the substance of things hoped for, the evidence of things not seen.', 'hope'),
('Micah 7:7', 'Therefore I will look unto the LORD; I will wait for the God of my salvation: my God will hear me.', 'hope'),
('Psalm 25:5', 'Lead me in thy truth, and teach me: for thou art the God of my salvation; on thee do I wait all the day.', 'hope'),

-- FAITH (18 verses)
('Hebrews 11:1', 'Now faith is the substance of things hoped for, the evidence of things not seen.', 'faith'),
('Romans 10:17', 'So then faith cometh by hearing, and hearing by the word of God.', 'faith'),
('2 Corinthians 5:7', 'For we walk by faith, not by sight.', 'faith'),
('Matthew 17:20', 'And Jesus said unto them, Because of your unbelief: for verily I say unto you, If ye have faith as a grain of mustard seed, ye shall say unto this mountain, Remove hence to yonder place; and it shall remove; and nothing shall be impossible unto you.', 'faith'),
('Mark 11:24', 'Therefore I say unto you, What things soever ye desire, when ye pray, believe that ye receive them, and ye shall have them.', 'faith'),
('Ephesians 2:8-9', 'For by grace are ye saved through faith; and that not of yourselves: it is the gift of God: Not of works, lest any man should boast.', 'faith'),
('Galatians 2:20', 'I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me: and the life which I now live in the flesh I live by the faith of the Son of God, who loved me, and gave himself for me.', 'faith'),
('James 2:17', 'Even so faith, if it hath not works, is dead, being alone.', 'faith'),
('1 John 5:4', 'For whatsoever is born of God overcometh the world: and this is the victory that overcometh the world, even our faith.', 'faith'),
('Romans 1:17', 'For therein is the righteousness of God revealed from faith to faith: as it is written, The just shall live by faith.', 'faith'),
('Mark 9:23', 'Jesus said unto him, If thou canst believe, all things are possible to him that believeth.', 'faith'),
('Hebrews 11:6', 'But without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him.', 'faith'),
('Romans 4:20-21', 'He staggered not at the promise of God through unbelief; but was strong in faith, giving glory to God; And being fully persuaded that, what he had promised, he was able also to perform.', 'faith'),
('Matthew 21:22', 'And all things, whatsoever ye shall ask in prayer, believing, ye shall receive.', 'faith'),
('1 Peter 1:7', 'That the trial of your faith, being much more precious than of gold that perisheth, though it be tried with fire, might be found unto praise and honour and glory at the appearing of Jesus Christ.', 'faith'),
('Habakkuk 2:4', 'Behold, his soul which is lifted up is not upright in him: but the just shall live by his faith.', 'faith'),
('Luke 17:6', 'And the Lord said, If ye had faith as a grain of mustard seed, ye might say unto this sycamine tree, Be thou plucked up by the root, and be thou planted in the sea; and it should obey you.', 'faith'),
('Hebrews 12:2', 'Looking unto Jesus the author and finisher of our faith; who for the joy that was set before him endured the cross, despising the shame, and is set down at the right hand of the throne of God.', 'faith'),

-- LOVE (19 verses)
('1 Corinthians 13:4-5', 'Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up, Doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh no evil.', 'love'),
('John 3:16', 'For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.', 'love'),
('1 John 4:19', 'We love him, because he first loved us.', 'love'),
('Romans 8:38-39', 'For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come, Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord.', 'love'),
('1 John 4:8', 'He that loveth not knoweth not God; for God is love.', 'love'),
('Jeremiah 31:3', 'The LORD hath appeared of old unto me, saying, Yea, I have loved thee with an everlasting love: therefore with lovingkindness have I drawn thee.', 'love'),
('1 Corinthians 13:13', 'And now abideth faith, hope, charity, these three; but the greatest of these is charity.', 'love'),
('1 John 3:18', 'My little children, let us not love in word, neither in tongue; but in deed and in truth.', 'love'),
('John 15:13', 'Greater love hath no man than this, that a man lay down his life for his friends.', 'love'),
('Ephesians 3:17-19', 'That Christ may dwell in your hearts by faith; that ye, being rooted and grounded in love, May be able to comprehend with all saints what is the breadth, and length, and depth, and height; And to know the love of Christ, which passeth knowledge, that ye might be filled with all the fulness of God.', 'love'),
('Deuteronomy 7:9', 'Know therefore that the LORD thy God, he is God, the faithful God, which keepeth covenant and mercy with them that love him and keep his commandments to a thousand generations.', 'love'),
('Psalm 36:7', 'How excellent is thy lovingkindness, O God! therefore the children of men put their trust under the shadow of thy wings.', 'love'),
('1 Peter 4:8', 'And above all things have fervent charity among yourselves: for charity shall cover the multitude of sins.', 'love'),
('Song of Solomon 8:7', 'Many waters cannot quench love, neither can the floods drown it: if a man would give all the substance of his house for love, it would utterly be contemned.', 'love'),
('Romans 5:8', 'But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.', 'love'),
('Zephaniah 3:17', 'The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing.', 'love'),
('Mark 12:30-31', 'And thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind, and with all thy strength: this is the first commandment. And the second is like, namely this, Thou shalt love thy neighbour as thyself.', 'love'),
('John 13:34', 'A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another.', 'love'),
('Psalm 86:15', 'But thou, O Lord, art a God full of compassion, and gracious, longsuffering, and plenteous in mercy and truth.', 'love'),

-- GUIDANCE (18 verses)
('Proverbs 3:5-6', 'Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.', 'guidance'),
('Psalm 32:8', 'I will instruct thee and teach thee in the way which thou shalt go: I will guide thee with mine eye.', 'guidance'),
('Psalm 119:105', 'Thy word is a lamp unto my feet, and a light unto my path.', 'guidance'),
('Isaiah 30:21', 'And thine ears shall hear a word behind thee, saying, This is the way, walk ye in it, when ye turn to the right hand, and when ye turn to the left.', 'guidance'),
('Psalm 37:23', 'The steps of a good man are ordered by the LORD: and he delighteth in his way.', 'guidance'),
('Proverbs 16:9', 'A man''s heart deviseth his way: but the LORD directeth his steps.', 'guidance'),
('Psalm 48:14', 'For this God is our God for ever and ever: he will be our guide even unto death.', 'guidance'),
('Isaiah 58:11', 'And the LORD shall guide thee continually, and satisfy thy soul in drought, and make fat thy bones: and thou shalt be like a watered garden, and like a spring of water, whose waters fail not.', 'guidance'),
('John 16:13', 'Howbeit when he, the Spirit of truth, is come, he will guide you into all truth.', 'guidance'),
('Psalm 25:9', 'The meek will he guide in judgment: and the meek will he teach his way.', 'guidance'),
('Proverbs 4:11', 'I have taught thee in the way of wisdom; I have led thee in right paths.', 'guidance'),
('Psalm 73:24', 'Thou shalt guide me with thy counsel, and afterward receive me to glory.', 'guidance'),
('Psalm 143:10', 'Teach me to do thy will; for thou art my God: thy spirit is good; lead me into the land of uprightness.', 'guidance'),
('Isaiah 42:16', 'And I will bring the blind by a way that they knew not; I will lead them in paths that they have not known: I will make darkness light before them, and crooked things straight.', 'guidance'),
('Psalm 23:2-3', 'He maketh me to lie down in green pastures: he leadeth me beside the still waters. He restoreth my soul: he leadeth me in the paths of righteousness for his name''s sake.', 'guidance'),
('Proverbs 16:3', 'Commit thy works unto the LORD, and thy thoughts shall be established.', 'guidance'),
('Psalm 25:4-5', 'Shew me thy ways, O LORD; teach me thy paths. Lead me in thy truth, and teach me: for thou art the God of my salvation; on thee do I wait all the day.', 'guidance'),
('Romans 8:14', 'For as many as are led by the Spirit of God, they are the sons of God.', 'guidance'),

-- GRATITUDE (18 verses)
('1 Thessalonians 5:18', 'In every thing give thanks: for this is the will of God in Christ Jesus concerning you.', 'gratitude'),
('Psalm 107:1', 'O give thanks unto the LORD, for he is good: for his mercy endureth for ever.', 'gratitude'),
('Colossians 3:17', 'And whatsoever ye do in word or deed, do all in the name of the Lord Jesus, giving thanks to God and the Father by him.', 'gratitude'),
('Psalm 118:24', 'This is the day which the LORD hath made; we will rejoice and be glad in it.', 'gratitude'),
('Psalm 136:1', 'O give thanks unto the LORD; for he is good: for his mercy endureth for ever.', 'gratitude'),
('Psalm 100:4-5', 'Enter into his gates with thanksgiving, and into his courts with praise: be thankful unto him, and bless his name. For the LORD is good; his mercy is everlasting; and his truth endureth to all generations.', 'gratitude'),
('James 1:17', 'Every good gift and every perfect gift is from above, and cometh down from the Father of lights, with whom is no variableness, neither shadow of turning.', 'gratitude'),
('Psalm 9:1', 'I will praise thee, O LORD, with my whole heart; I will shew forth all thy marvellous works.', 'gratitude'),
('Ephesians 5:20', 'Giving thanks always for all things unto God and the Father in the name of our Lord Jesus Christ.', 'gratitude'),
('Psalm 106:1', 'Praise ye the LORD. O give thanks unto the LORD; for he is good: for his mercy endureth for ever.', 'gratitude'),
('Philippians 4:6', 'Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.', 'gratitude'),
('Psalm 50:14', 'Offer unto God thanksgiving; and pay thy vows unto the most High.', 'gratitude'),
('1 Chronicles 16:34', 'O give thanks unto the LORD; for he is good; for his mercy endureth for ever.', 'gratitude'),
('Psalm 69:30', 'I will praise the name of God with a song, and will magnify him with thanksgiving.', 'gratitude'),
('Colossians 2:7', 'Rooted and built up in him, and stablished in the faith, as ye have been taught, abounding therein with thanksgiving.', 'gratitude'),
('Daniel 2:23', 'I thank thee, and praise thee, O thou God of my fathers, who hast given me wisdom and might, and hast made known unto me now what we desired of thee.', 'gratitude'),
('Psalm 75:1', 'Unto thee, O God, do we give thanks, unto thee do we give thanks: for that thy name is near thy wondrous works declare.', 'gratitude'),
('2 Corinthians 9:15', 'Thanks be unto God for his unspeakable gift.', 'gratitude'),

-- COURAGE (18 verses)
('Joshua 1:9', 'Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.', 'courage'),
('Deuteronomy 31:6', 'Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.', 'courage'),
('Isaiah 41:10', 'Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.', 'courage'),
('Psalm 27:14', 'Wait on the LORD: be of good courage, and he shall strengthen thine heart: wait, I say, on the LORD.', 'courage'),
('2 Timothy 1:7', 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.', 'courage'),
('Psalm 56:3', 'What time I am afraid, I will trust in thee.', 'courage'),
('Isaiah 43:1', 'But now thus saith the LORD that created thee, O Jacob, and he that formed thee, O Israel, Fear not: for I have redeemed thee, I have called thee by thy name; thou art mine.', 'courage'),
('Psalm 118:6', 'The LORD is on my side; I will not fear: what can man do unto me?', 'courage'),
('Romans 8:31', 'What shall we then say to these things? If God be for us, who can be against us?', 'courage'),
('1 Chronicles 28:20', 'And David said to Solomon his son, Be strong and of good courage, and do it: fear not, nor be dismayed: for the LORD God, even my God, will be with thee.', 'courage'),
('Psalm 31:24', 'Be of good courage, and he shall strengthen your heart, all ye that hope in the LORD.', 'courage'),
('Proverbs 28:1', 'The wicked flee when no man pursueth: but the righteous are bold as a lion.', 'courage'),
('Psalm 112:7', 'He shall not be afraid of evil tidings: his heart is fixed, trusting in the LORD.', 'courage'),
('Isaiah 35:4', 'Say to them that are of a fearful heart, Be strong, fear not: behold, your God will come with vengeance, even God with a recompence; he will come and save you.', 'courage'),
('Acts 4:31', 'And when they had prayed, the place was shaken where they were assembled together; and they were all filled with the Holy Ghost, and they spake the word of God with boldness.', 'courage'),
('Psalm 23:4', 'Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.', 'courage'),
('John 14:27', 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.', 'courage'),
('Hebrews 13:6', 'So that we may boldly say, The Lord is my helper, and I will not fear what man shall do unto me.', 'courage'),

-- PATIENCE (18 verses)
('James 1:2-4', 'My brethren, count it all joy when ye fall into divers temptations; Knowing this, that the trying of your faith worketh patience. But let patience have her perfect work, that ye may be perfect and entire, wanting nothing.', 'patience'),
('Romans 12:12', 'Rejoicing in hope; patient in tribulation; continuing instant in prayer.', 'patience'),
('Ecclesiastes 7:8', 'Better is the end of a thing than the beginning thereof: and the patient in spirit is better than the proud in spirit.', 'patience'),
('Galatians 6:9', 'And let us not be weary in well doing: for in due season we shall reap, if we faint not.', 'patience'),
('Psalm 37:7', 'Rest in the LORD, and wait patiently for him: fret not thyself because of him who prospereth in his way.', 'patience'),
('Hebrews 10:36', 'For ye have need of patience, that, after ye have done the will of God, ye might receive the promise.', 'patience'),
('Isaiah 40:31', 'But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.', 'patience'),
('Psalm 40:1', 'I waited patiently for the LORD; and he inclined unto me, and heard my cry.', 'patience'),
('Romans 8:25', 'But if we hope for that we see not, then do we with patience wait for it.', 'patience'),
('Colossians 1:11', 'Strengthened with all might, according to his glorious power, unto all patience and longsuffering with joyfulness.', 'patience'),
('Proverbs 14:29', 'He that is slow to wrath is of great understanding: but he that is hasty of spirit exalteth folly.', 'patience'),
('2 Peter 3:9', 'The Lord is not slack concerning his promise, as some men count slackness; but is longsuffering to us-ward, not willing that any should perish, but that all should come to repentance.', 'patience'),
('Lamentations 3:25', 'The LORD is good unto them that wait for him, to the soul that seeketh him.', 'patience'),
('Proverbs 15:18', 'A wrathful man stirreth up strife: but he that is slow to anger appeaseth strife.', 'patience'),
('1 Corinthians 13:4', 'Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up.', 'patience'),
('Psalm 27:14', 'Wait on the LORD: be of good courage, and he shall strengthen thine heart: wait, I say, on the LORD.', 'patience'),
('Habakkuk 2:3', 'For the vision is yet for an appointed time, but at the end it shall speak, and not lie: though it tarry, wait for it; because it will surely come, it will not tarry.', 'patience'),
('James 5:7-8', 'Be patient therefore, brethren, unto the coming of the Lord. Behold, the husbandman waiteth for the precious fruit of the earth, and hath long patience for it, until he receive the early and latter rain. Be ye also patient; stablish your hearts: for the coming of the Lord draweth nigh.', 'patience'),

-- JOY (18 verses)
('Nehemiah 8:10', 'Then he said unto them, Go your way, eat the fat, and drink the sweet, and send portions unto them for whom nothing is prepared: for this day is holy unto our Lord: neither be ye sorry; for the joy of the LORD is your strength.', 'joy'),
('Psalm 16:11', 'Thou wilt shew me the path of life: in thy presence is fulness of joy; at thy right hand there are pleasures for evermore.', 'joy'),
('John 15:11', 'These things have I spoken unto you, that my joy might remain in you, and that your joy might be full.', 'joy'),
('Psalm 30:5', 'For his anger endureth but a moment; in his favour is life: weeping may endure for a night, but joy cometh in the morning.', 'joy'),
('Romans 15:13', 'Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.', 'joy'),
('Philippians 4:4', 'Rejoice in the Lord alway: and again I say, Rejoice.', 'joy'),
('James 1:2', 'My brethren, count it all joy when ye fall into divers temptations.', 'joy'),
('Psalm 126:5', 'They that sow in tears shall reap in joy.', 'joy'),
('Psalm 5:11', 'But let all those that put their trust in thee rejoice: let them ever shout for joy, because thou defendest them: let them also that love thy name be joyful in thee.', 'joy'),
('Isaiah 61:10', 'I will greatly rejoice in the LORD, my soul shall be joyful in my God; for he hath clothed me with the garments of salvation, he hath covered me with the robe of righteousness.', 'joy'),
('1 Peter 1:8', 'Whom having not seen, ye love; in whom, though now ye see him not, yet believing, ye rejoice with joy unspeakable and full of glory.', 'joy'),
('Psalm 98:4', 'Make a joyful noise unto the LORD, all the earth: make a loud noise, and rejoice, and sing praise.', 'joy'),
('Psalm 47:1', 'O clap your hands, all ye people; shout unto God with the voice of triumph.', 'joy'),
('Psalm 118:24', 'This is the day which the LORD hath made; we will rejoice and be glad in it.', 'joy'),
('Habakkuk 3:18', 'Yet I will rejoice in the LORD, I will joy in the God of my salvation.', 'joy'),
('Zephaniah 3:17', 'The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing.', 'joy'),
('Galatians 5:22', 'But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith.', 'joy'),
('John 16:22', 'And ye now therefore have sorrow: but I will see you again, and your heart shall rejoice, and your joy no man taketh from you.', 'joy'),

-- TRUST (18 verses)
('Proverbs 3:5', 'Trust in the LORD with all thine heart; and lean not unto thine own understanding.', 'trust'),
('Psalm 56:3-4', 'What time I am afraid, I will trust in thee. In God I will praise his word, in God I have put my trust; I will not fear what flesh can do unto me.', 'trust'),
('Psalm 37:5', 'Commit thy way unto the LORD; trust also in him; and he shall bring it to pass.', 'trust'),
('Psalm 9:10', 'And they that know thy name will put their trust in thee: for thou, LORD, hast not forsaken them that seek thee.', 'trust'),
('Psalm 62:8', 'Trust in him at all times; ye people, pour out your heart before him: God is a refuge for us.', 'trust'),
('Psalm 20:7', 'Some trust in chariots, and some in horses: but we will remember the name of the LORD our God.', 'trust'),
('Psalm 115:11', 'Ye that fear the LORD, trust in the LORD: he is their help and their shield.', 'trust'),
('Nahum 1:7', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'trust'),
('Psalm 125:1', 'They that trust in the LORD shall be as mount Zion, which cannot be removed, but abideth for ever.', 'trust'),
('Psalm 91:2', 'I will say of the LORD, He is my refuge and my fortress: my God; in him will I trust.', 'trust'),
('Psalm 37:3', 'Trust in the LORD, and do good; so shalt thou dwell in the land, and verily thou shalt be fed.', 'trust'),
('Isaiah 12:2', 'Behold, God is my salvation; I will trust, and not be afraid: for the LORD JEHOVAH is my strength and my song; he also is become my salvation.', 'trust'),
('Psalm 5:11', 'But let all those that put their trust in thee rejoice: let them ever shout for joy, because thou defendest them: let them also that love thy name be joyful in thee.', 'trust'),
('Psalm 28:7', 'The LORD is my strength and my shield; my heart trusted in him, and I am helped.', 'trust'),
('Psalm 40:4', 'Blessed is that man that maketh the LORD his trust, and respecteth not the proud, nor such as turn aside to lies.', 'trust'),
('Psalm 84:12', 'O LORD of hosts, blessed is the man that trusteth in thee.', 'trust'),
('Psalm 143:8', 'Cause me to hear thy lovingkindness in the morning; for in thee do I trust: cause me to know the way wherein I should walk; for I lift up my soul unto thee.', 'trust'),
('Jeremiah 17:7', 'Blessed is the man that trusteth in the LORD, and whose hope the LORD is.', 'trust'),

-- PROVISION (18 verses)
('Philippians 4:19', 'But my God shall supply all your need according to his riches in glory by Christ Jesus.', 'provision'),
('Matthew 6:33', 'But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.', 'provision'),
('Psalm 23:1', 'The LORD is my shepherd; I shall not want.', 'provision'),
('Psalm 37:25', 'I have been young, and now am old; yet have I not seen the righteous forsaken, nor his seed begging bread.', 'provision'),
('Deuteronomy 8:18', 'But thou shalt remember the LORD thy God: for it is he that giveth thee power to get wealth.', 'provision'),
('Luke 12:24', 'Consider the ravens: for they neither sow nor reap; which neither have storehouse nor barn; and God feedeth them: how much more are ye better than the fowls?', 'provision'),
('Matthew 6:26', 'Behold the fowls of the air: for they sow not, neither do they reap, nor gather into barns; yet your heavenly Father feedeth them. Are ye not much better than they?', 'provision'),
('Psalm 34:10', 'The young lions do lack, and suffer hunger: but they that seek the LORD shall not want any good thing.', 'provision'),
('Psalm 145:15-16', 'The eyes of all wait upon thee; and thou givest them their meat in due season. Thou openest thine hand, and satisfiest the desire of every living thing.', 'provision'),
('Genesis 22:14', 'And Abraham called the name of that place Jehovahjireh: as it is said to this day, In the mount of the LORD it shall be seen.', 'provision'),
('2 Corinthians 9:8', 'And God is able to make all grace abound toward you; that ye, always having all sufficiency in all things, may abound to every good work.', 'provision'),
('Psalm 111:5', 'He hath given meat unto them that fear him: he will ever be mindful of his covenant.', 'provision'),
('Psalm 132:15', 'I will abundantly bless her provision: I will satisfy her poor with bread.', 'provision'),
('Joel 2:26', 'And ye shall eat in plenty, and be satisfied, and praise the name of the LORD your God, that hath dealt wondrously with you: and my people shall never be ashamed.', 'provision'),
('Proverbs 10:3', 'The LORD will not suffer the soul of the righteous to famish.', 'provision'),
('Isaiah 58:11', 'And the LORD shall guide thee continually, and satisfy thy soul in drought.', 'provision'),
('Malachi 3:10', 'Bring ye all the tithes into the storehouse, that there may be meat in mine house, and prove me now herewith, saith the LORD of hosts, if I will not open you the windows of heaven, and pour you out a blessing, that there shall not be room enough to receive it.', 'provision'),
('Psalm 68:19', 'Blessed be the Lord, who daily loadeth us with benefits, even the God of our salvation.', 'provision'),

-- PROTECTION (18 verses)
('Psalm 91:1-2', 'He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty. I will say of the LORD, He is my refuge and my fortress: my God; in him will I trust.', 'protection'),
('Psalm 121:7-8', 'The LORD shall preserve thee from all evil: he shall preserve thy soul. The LORD shall preserve thy going out and thy coming in from this time forth, and even for evermore.', 'protection'),
('Psalm 34:7', 'The angel of the LORD encampeth round about them that fear him, and delivereth them.', 'protection'),
('Psalm 18:2', 'The LORD is my rock, and my fortress, and my deliverer; my God, my strength, in whom I will trust; my buckler, and the horn of my salvation, and my high tower.', 'protection'),
('Psalm 91:11', 'For he shall give his angels charge over thee, to keep thee in all thy ways.', 'protection'),
('2 Thessalonians 3:3', 'But the Lord is faithful, who shall stablish you, and keep you from evil.', 'protection'),
('Psalm 32:7', 'Thou art my hiding place; thou shalt preserve me from trouble; thou shalt compass me about with songs of deliverance.', 'protection'),
('Proverbs 18:10', 'The name of the LORD is a strong tower: the righteous runneth into it, and is safe.', 'protection'),
('Psalm 46:1', 'God is our refuge and strength, a very present help in trouble.', 'protection'),
('Isaiah 54:17', 'No weapon that is formed against thee shall prosper; and every tongue that shall rise against thee in judgment thou shalt condemn.', 'protection'),
('Psalm 121:3-4', 'He will not suffer thy foot to be moved: he that keepeth thee will not slumber. Behold, he that keepeth Israel shall neither slumber nor sleep.', 'protection'),
('Psalm 91:4', 'He shall cover thee with his feathers, and under his wings shalt thou trust: his truth shall be thy shield and buckler.', 'protection'),
('Psalm 59:16', 'But I will sing of thy power; yea, I will sing aloud of thy mercy in the morning: for thou hast been my defence and refuge in the day of my trouble.', 'protection'),
('Psalm 144:2', 'My goodness, and my fortress; my high tower, and my deliverer; my shield, and he in whom I trust.', 'protection'),
('Psalm 3:3', 'But thou, O LORD, art a shield for me; my glory, and the lifter up of mine head.', 'protection'),
('Deuteronomy 33:27', 'The eternal God is thy refuge, and underneath are the everlasting arms.', 'protection'),
('Psalm 61:3', 'For thou hast been a shelter for me, and a strong tower from the enemy.', 'protection'),
('2 Samuel 22:3', 'The God of my rock; in him will I trust: he is my shield, and the horn of my salvation, my high tower, and my refuge, my saviour; thou savest me from violence.', 'protection'),

-- HEALING (18 verses)
('Psalm 103:2-3', 'Bless the LORD, O my soul, and forget not all his benefits: Who forgiveth all thine iniquities; who healeth all thy diseases.', 'healing'),
('Jeremiah 17:14', 'Heal me, O LORD, and I shall be healed; save me, and I shall be saved: for thou art my praise.', 'healing'),
('James 5:15', 'And the prayer of faith shall save the sick, and the Lord shall raise him up; and if he have committed sins, they shall be forgiven him.', 'healing'),
('Isaiah 53:5', 'But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed.', 'healing'),
('Exodus 15:26', 'And said, If thou wilt diligently hearken to the voice of the LORD thy God, and wilt do that which is right in his sight, and wilt give ear to his commandments, and keep all his statutes, I will put none of these diseases upon thee, which I have brought upon the Egyptians: for I am the LORD that healeth thee.', 'healing'),
('Psalm 147:3', 'He healeth the broken in heart, and bindeth up their wounds.', 'healing'),
('3 John 1:2', 'Beloved, I wish above all things that thou mayest prosper and be in health, even as thy soul prospereth.', 'healing'),
('Proverbs 17:22', 'A merry heart doeth good like a medicine: but a broken spirit drieth the bones.', 'healing'),
('Psalm 41:3', 'The LORD will strengthen him upon the bed of languishing: thou wilt make all his bed in his sickness.', 'healing'),
('Matthew 9:35', 'And Jesus went about all the cities and villages, teaching in their synagogues, and preaching the gospel of the kingdom, and healing every sickness and every disease among the people.', 'healing'),
('Isaiah 57:18', 'I have seen his ways, and will heal him: I will lead him also, and restore comforts unto him and to his mourners.', 'healing'),
('Malachi 4:2', 'But unto you that fear my name shall the Sun of righteousness arise with healing in his wings.', 'healing'),
('Psalm 30:2', 'O LORD my God, I cried unto thee, and thou hast healed me.', 'healing'),
('Proverbs 4:20-22', 'My son, attend to my words; incline thine ear unto my sayings. Let them not depart from thine eyes; keep them in the midst of thine heart. For they are life unto those that find them, and health to all their flesh.', 'healing'),
('James 5:16', 'Confess your faults one to another, and pray one for another, that ye may be healed. The effectual fervent prayer of a righteous man availeth much.', 'healing'),
('Hosea 6:1', 'Come, and let us return unto the LORD: for he hath torn, and he will heal us; he hath smitten, and he will bind us up.', 'healing'),
('Psalm 107:20', 'He sent his word, and healed them, and delivered them from their destructions.', 'healing'),
('Isaiah 38:16', 'O Lord, by these things men live, and in all these things is the life of my spirit: so wilt thou recover me, and make me to live.', 'healing'),

-- FORGIVENESS (18 verses)
('1 John 1:9', 'If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness.', 'forgiveness'),
('Ephesians 4:32', 'And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ''s sake hath forgiven you.', 'forgiveness'),
('Psalm 103:12', 'As far as the east is from the west, so far hath he removed our transgressions from us.', 'forgiveness'),
('Colossians 3:13', 'Forbearing one another, and forgiving one another, if any man have a quarrel against any: even as Christ forgave you, so also do ye.', 'forgiveness'),
('Isaiah 1:18', 'Come now, and let us reason together, saith the LORD: though your sins be as scarlet, they shall be as white as snow; though they be red like crimson, they shall be as wool.', 'forgiveness'),
('Micah 7:18-19', 'Who is a God like unto thee, that pardoneth iniquity, and passeth by the transgression of the remnant of his heritage? he retaineth not his anger for ever, because he delighteth in mercy. He will turn again, he will have compassion upon us; he will subdue our iniquities; and thou wilt cast all their sins into the depths of the sea.', 'forgiveness'),
('Psalm 32:1', 'Blessed is he whose transgression is forgiven, whose sin is covered.', 'forgiveness'),
('Acts 3:19', 'Repent ye therefore, and be converted, that your sins may be blotted out, when the times of refreshing shall come from the presence of the Lord.', 'forgiveness'),
('Matthew 6:14', 'For if ye forgive men their trespasses, your heavenly Father will also forgive you.', 'forgiveness'),
('Romans 8:1', 'There is therefore now no condemnation to them which are in Christ Jesus, who walk not after the flesh, but after the Spirit.', 'forgiveness'),
('2 Chronicles 7:14', 'If my people, which are called by my name, shall humble themselves, and pray, and seek my face, and turn from their wicked ways; then will I hear from heaven, and will forgive their sin, and will heal their land.', 'forgiveness'),
('Psalm 86:5', 'For thou, Lord, art good, and ready to forgive; and plenteous in mercy unto all them that call upon thee.', 'forgiveness'),
('Isaiah 43:25', 'I, even I, am he that blotteth out thy transgressions for mine own sake, and will not remember thy sins.', 'forgiveness'),
('Hebrews 8:12', 'For I will be merciful to their unrighteousness, and their sins and their iniquities will I remember no more.', 'forgiveness'),
('Luke 6:37', 'Judge not, and ye shall not be judged: condemn not, and ye shall not be condemned: forgive, and ye shall be forgiven.', 'forgiveness'),
('Psalm 130:3-4', 'If thou, LORD, shouldest mark iniquities, O Lord, who shall stand? But there is forgiveness with thee, that thou mayest be feared.', 'forgiveness'),
('Matthew 18:21-22', 'Then came Peter to him, and said, Lord, how oft shall my brother sin against me, and I forgive him? till seven times? Jesus saith unto him, I say not unto thee, Until seven times: but, Until seventy times seven.', 'forgiveness'),
('Jeremiah 31:34', 'And they shall teach no more every man his neighbour, and every man his brother, saying, Know the LORD: for they shall all know me, from the least of them unto the greatest of them, saith the LORD: for I will forgive their iniquity, and I will remember their sin no more.', 'forgiveness'),

-- PURPOSE (19 verses)
('Jeremiah 29:11', 'For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.', 'purpose'),
('Romans 8:28', 'And we know that all things work together for good to them that love God, to them who are the called according to his purpose.', 'purpose'),
('Ephesians 2:10', 'For we are his workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should walk in them.', 'purpose'),
('Proverbs 19:21', 'There are many devices in a man''s heart; nevertheless the counsel of the LORD, that shall stand.', 'purpose'),
('Psalm 138:8', 'The LORD will perfect that which concerneth me: thy mercy, O LORD, endureth for ever: forsake not the works of thine own hands.', 'purpose'),
('Philippians 2:13', 'For it is God which worketh in you both to will and to do of his good pleasure.', 'purpose'),
('Isaiah 46:10', 'Declaring the end from the beginning, and from ancient times the things that are not yet done, saying, My counsel shall stand, and I will do all my pleasure.', 'purpose'),
('Proverbs 16:4', 'The LORD hath made all things for himself: yea, even the wicked for the day of evil.', 'purpose'),
('Colossians 1:16', 'For by him were all things created, that are in heaven, and that are in earth, visible and invisible, whether they be thrones, or dominions, or principalities, or powers: all things were created by him, and for him.', 'purpose'),
('Psalm 57:2', 'I will cry unto God most high; unto God that performeth all things for me.', 'purpose'),
('Isaiah 14:27', 'For the LORD of hosts hath purposed, and who shall disannul it? and his hand is stretched out, and who shall turn it back?', 'purpose'),
('Psalm 33:11', 'The counsel of the LORD standeth for ever, the thoughts of his heart to all generations.', 'purpose'),
('Romans 12:2', 'And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God.', 'purpose'),
('Ecclesiastes 3:1', 'To every thing there is a season, and a time to every purpose under the heaven.', 'purpose'),
('2 Timothy 1:9', 'Who hath saved us, and called us with an holy calling, not according to our works, but according to his own purpose and grace, which was given us in Christ Jesus before the world began.', 'purpose'),
('1 Peter 2:9', 'But ye are a chosen generation, a royal priesthood, an holy nation, a peculiar people; that ye should shew forth the praises of him who hath called you out of darkness into his marvellous light.', 'purpose'),
('Esther 4:14', 'For if thou altogether holdest thy peace at this time, then shall there enlargement and deliverance arise to the Jews from another place; but thou and thy father''s house shall be destroyed: and who knoweth whether thou art come to the kingdom for such a time as this?', 'purpose'),
('Proverbs 16:9', 'A man''s heart deviseth his way: but the LORD directeth his steps.', 'purpose'),
('Matthew 5:16', 'Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.', 'purpose'),

-- PRAYER (19 verses)
('Matthew 7:7', 'Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you.', 'prayer'),
('Philippians 4:6', 'Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.', 'prayer'),
('1 Thessalonians 5:17', 'Pray without ceasing.', 'prayer'),
('Jeremiah 33:3', 'Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not.', 'prayer'),
('James 5:16', 'Confess your faults one to another, and pray one for another, that ye may be healed. The effectual fervent prayer of a righteous man availeth much.', 'prayer'),
('Psalm 145:18', 'The LORD is nigh unto all them that call upon him, to all that call upon him in truth.', 'prayer'),
('1 John 5:14', 'And this is the confidence that we have in him, that, if we ask any thing according to his will, he heareth us.', 'prayer'),
('Matthew 6:6', 'But thou, when thou prayest, enter into thy closet, and when thou hast shut thy door, pray to thy Father which is in secret; and thy Father which seeth in secret shall reward thee openly.', 'prayer'),
('Mark 11:24', 'Therefore I say unto you, What things soever ye desire, when ye pray, believe that ye receive them, and ye shall have them.', 'prayer'),
('Psalm 34:17', 'The righteous cry, and the LORD heareth, and delivereth them out of all their troubles.', 'prayer'),
('Romans 8:26', 'Likewise the Spirit also helpeth our infirmities: for we know not what we should pray for as we ought: but the Spirit itself maketh intercession for us with groanings which cannot be uttered.', 'prayer'),
('2 Chronicles 7:14', 'If my people, which are called by my name, shall humble themselves, and pray, and seek my face, and turn from their wicked ways; then will I hear from heaven, and will forgive their sin, and will heal their land.', 'prayer'),
('Psalm 65:2', 'O thou that hearest prayer, unto thee shall all flesh come.', 'prayer'),
('Isaiah 65:24', 'And it shall come to pass, that before they call, I will answer; and while they are yet speaking, I will hear.', 'prayer'),
('John 15:7', 'If ye abide in me, and my words abide in you, ye shall ask what ye will, and it shall be done unto you.', 'prayer'),
('Psalm 91:15', 'He shall call upon me, and I will answer him: I will be with him in trouble; I will deliver him, and honour him.', 'prayer'),
('Hebrews 4:16', 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy, and find grace to help in time of need.', 'prayer'),
('Luke 11:9', 'And I say unto you, Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you.', 'prayer'),
('Psalm 17:6', 'I have called upon thee, for thou wilt hear me, O God: incline thine ear unto me, and hear my speech.', 'prayer');
