-- Seek Daily Verses Seed Data (364 NLT verses across 20 themes)
-- Generated to match the KJV verses in seed.sql

INSERT INTO daily_verses (reference, text, theme, translation) VALUES
-- STRENGTH (18 verses)
('Isaiah 40:31', 'But those who trust in the LORD will find new strength. They will soar high on wings like eagles. They will run and not grow weary. They will walk and not faint.', 'strength', 'NLT'),
('Philippians 4:13', 'For I can do everything through Christ, who gives me strength.', 'strength', 'NLT'),
('Psalm 46:1', 'God is our refuge and strength, always ready to help in times of trouble.', 'strength', 'NLT'),
('2 Corinthians 12:9', 'Each time he said, "My grace is all you need. My power works best in weakness."', 'strength', 'NLT'),
('Deuteronomy 31:6', 'So be strong and courageous! Do not be afraid and do not panic before them. For the LORD your God will personally go ahead of you. He will neither fail you nor abandon you.', 'strength', 'NLT'),
('Psalm 73:26', 'My health may fail, and my spirit may grow weak, but God remains the strength of my heart; he is mine forever.', 'strength', 'NLT'),
('Isaiah 41:10', 'Don''t be afraid, for I am with you. Don''t be discouraged, for I am your God. I will strengthen you and help you. I will hold you up with my victorious right hand.', 'strength', 'NLT'),
('Nehemiah 8:10', 'And Nehemiah continued, "Go and celebrate with a feast of rich foods and sweet drinks, and share gifts of food with people who have nothing prepared. This is a sacred day before our Lord. Don''t be dejected and sad, for the joy of the LORD is your strength!"', 'strength', 'NLT'),
('Psalm 18:32', 'God arms me with strength, and he makes my way perfect.', 'strength', 'NLT'),
('Psalm 27:1', 'The LORD is my light and my salvation — so why should I be afraid? The LORD is my fortress, protecting me from danger, so why should I tremble?', 'strength', 'NLT'),
('Psalm 28:7', 'The LORD is my strength and shield. I trust him with all my heart. He helps me, and my heart is filled with joy. I burst out in songs of thanksgiving.', 'strength', 'NLT'),
('Psalm 29:11', 'The LORD gives his people strength. The LORD blesses them with peace.', 'strength', 'NLT'),
('Psalm 31:24', 'So be strong and courageous, all you who put your hope in the LORD!', 'strength', 'NLT'),
('Psalm 37:39', 'The LORD rescues the godly; he is their fortress in times of trouble.', 'strength', 'NLT'),
('Psalm 68:35', 'God is awesome in his sanctuary. The God of Israel gives power and strength to his people. Praise be to God!', 'strength', 'NLT'),
('Psalm 138:3', 'As soon as I pray, you answer me; you encourage me by giving me strength.', 'strength', 'NLT'),
('Habakkuk 3:19', 'The Sovereign LORD is my strength! He makes me as surefooted as a deer, able to tread upon the heights.', 'strength', 'NLT'),
('Ephesians 6:10', 'A final word: Be strong in the Lord and in his mighty power.', 'strength', 'NLT'),

-- PEACE (18 verses)
('John 14:27', 'I am leaving you with a gift — peace of mind and heart. And the peace I give is a gift the world cannot give. So don''t be troubled or afraid.', 'peace', 'NLT'),
('Philippians 4:6-7', 'Don''t worry about anything; instead, pray about everything. Tell God what you need, and thank him for all he has done. Then you will experience God''s peace, which exceeds anything we can understand. His peace will guard your hearts and minds as you live in Christ Jesus.', 'peace', 'NLT'),
('Isaiah 26:3', 'You will keep in perfect peace all who trust in you, all whose thoughts are fixed on you!', 'peace', 'NLT'),
('Romans 8:6', 'So letting your sinful nature control your mind leads to death. But letting the Spirit control your mind leads to life and peace.', 'peace', 'NLT'),
('Psalm 4:8', 'In peace I will lie down and sleep, for you alone, O LORD, will keep me safe.', 'peace', 'NLT'),
('Colossians 3:15', 'And let the peace that comes from Christ rule in your hearts. For as members of one body you are called to live in peace. And always be thankful.', 'peace', 'NLT'),
('Psalm 29:11', 'The LORD gives his people strength. The LORD blesses them with peace.', 'peace', 'NLT'),
('Romans 15:13', 'I pray that God, the source of hope, will fill you completely with joy and peace because you trust in him. Then you will overflow with confident hope through the power of the Holy Spirit.', 'peace', 'NLT'),
('Matthew 5:9', 'God blesses those who work for peace, for they will be called the children of God.', 'peace', 'NLT'),
('Psalm 119:165', 'Those who love your instructions have great peace and do not stumble.', 'peace', 'NLT'),
('Isaiah 9:6', 'For a child is born to us, a son is given to us. The government will rest on his shoulders. And he will be called: Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace.', 'peace', 'NLT'),
('John 16:33', 'I have told you all this so that you may have peace in me. Here on earth you will have many trials and sorrows. But take heart, because I have overcome the world.', 'peace', 'NLT'),
('2 Thessalonians 3:16', 'Now may the Lord of peace himself give you his peace at all times and in every situation. The Lord be with you all.', 'peace', 'NLT'),
('Numbers 6:26', 'May the LORD show you his favor and give you his peace.', 'peace', 'NLT'),
('Psalm 34:14', 'Turn away from evil and do good. Search for peace, and work to maintain it.', 'peace', 'NLT'),
('Isaiah 55:12', 'You will live in joy and peace. The mountains and hills will burst into song, and the trees of the field will clap their hands!', 'peace', 'NLT'),
('Romans 5:1', 'Therefore, since we have been made right in God''s sight by faith, we have peace with God because of what Jesus Christ our Lord has done for us.', 'peace', 'NLT'),
('Galatians 5:22', 'But the Holy Spirit produces this kind of fruit in our lives: love, joy, peace, patience, kindness, goodness, faithfulness.', 'peace', 'NLT'),

-- COMFORT (18 verses)
('Psalm 23:4', 'Even when I walk through the darkest valley, I will not be afraid, for you are close beside me. Your rod and your staff protect and comfort me.', 'comfort', 'NLT'),
('2 Corinthians 1:3-4', 'All praise to God, the Father of our Lord Jesus Christ. God is our merciful Father and the source of all comfort. He comforts us in all our troubles so that we can comfort others. When they are troubled, we will be able to give them the same comfort God has given us.', 'comfort', 'NLT'),
('Matthew 11:28', 'Then Jesus said, "Come to me, all of you who are weary and carry heavy burdens, and I will give you rest."', 'comfort', 'NLT'),
('Psalm 34:18', 'The LORD is close to the brokenhearted; he rescues those whose spirits are crushed.', 'comfort', 'NLT'),
('Isaiah 49:13', 'Sing for joy, O heavens! Rejoice, O earth! Burst into song, O mountains! For the LORD has comforted his people and will have compassion on them in their suffering.', 'comfort', 'NLT'),
('Psalm 147:3', 'He heals the brokenhearted and bandages their wounds.', 'comfort', 'NLT'),
('Revelation 21:4', 'He will wipe every tear from their eyes, and there will be no more death or sorrow or crying or pain. All these things are gone forever.', 'comfort', 'NLT'),
('Isaiah 41:13', 'For I hold you by your right hand — I, the LORD your God. And I say to you, "Don''t be afraid. I am here to help you."', 'comfort', 'NLT'),
('Psalm 55:22', 'Give your burdens to the LORD, and he will take care of you. He will not permit the godly to slip and fall.', 'comfort', 'NLT'),
('Romans 8:28', 'And we know that God causes everything to work together for the good of those who love God and are called according to his purpose for them.', 'comfort', 'NLT'),
('Psalm 94:19', 'When doubts filled my mind, your comfort gave me renewed hope and cheer.', 'comfort', 'NLT'),
('Isaiah 66:13', 'I will comfort you there in Jerusalem as a mother comforts her child.', 'comfort', 'NLT'),
('Psalm 30:5', 'For his anger lasts only a moment, but his favor lasts a lifetime! Weeping may last through the night, but joy comes with the morning.', 'comfort', 'NLT'),
('Lamentations 3:22-23', 'The faithful love of the LORD never ends! His mercies never cease. Great is his faithfulness; his mercies begin afresh each morning.', 'comfort', 'NLT'),
('2 Corinthians 4:17', 'For our present troubles are small and won''t last very long. Yet they produce for us a glory that vastly outweighs them and will last forever!', 'comfort', 'NLT'),
('Psalm 71:21', 'You will restore me to even greater honor and comfort me once again.', 'comfort', 'NLT'),
('John 14:1', 'Don''t let your hearts be troubled. Trust in God, and trust also in me.', 'comfort', 'NLT'),
('1 Peter 5:7', 'Give all your worries and cares to God, for he cares about you.', 'comfort', 'NLT'),

-- PRAISE (18 verses)
('Psalm 150:6', 'Let everything that breathes sing praises to the LORD! Praise the LORD!', 'praise', 'NLT'),
('Psalm 100:4', 'Enter his gates with thanksgiving; go into his courts with praise. Give thanks to him and praise his name.', 'praise', 'NLT'),
('Psalm 34:1', 'I will praise the LORD at all times. I will constantly speak his praises.', 'praise', 'NLT'),
('Hebrews 13:15', 'Therefore, let us offer through Jesus a continual sacrifice of praise to God, proclaiming our allegiance to his name.', 'praise', 'NLT'),
('Psalm 145:3', 'Great is the LORD! He is most worthy of praise! No one can measure his greatness.', 'praise', 'NLT'),
('Psalm 9:1-2', 'I will praise you, LORD, with all my heart; I will tell of all the marvelous things you have done. I will be filled with joy because of you. I will sing praises to your name, O Most High.', 'praise', 'NLT'),
('Psalm 95:1', 'Come, let us sing to the LORD! Let us shout joyfully to the Rock of our salvation.', 'praise', 'NLT'),
('Psalm 103:1', 'Let all that I am praise the LORD; with my whole heart, I will praise his holy name.', 'praise', 'NLT'),
('Psalm 113:3', 'Everywhere — from east to west — praise the name of the LORD.', 'praise', 'NLT'),
('Psalm 148:13', 'Let them all praise the name of the LORD. For his name is very great; his glory towers over the earth and heaven!', 'praise', 'NLT'),
('Psalm 96:4', 'Great is the LORD! He is most worthy of praise! He is to be feared above all gods.', 'praise', 'NLT'),
('Psalm 63:3', 'Your unfailing love is better than life itself; how I praise you!', 'praise', 'NLT'),
('Psalm 71:8', 'Let me shout your praises from morning to night.', 'praise', 'NLT'),
('Psalm 135:3', 'Praise the LORD, for the LORD is good; celebrate his lovely name with music.', 'praise', 'NLT'),
('Psalm 42:11', 'Why am I discouraged? Why is my heart so sad? I will put my hope in God! I will praise him again — my Savior and my God!', 'praise', 'NLT'),
('Acts 16:25', 'Around midnight Paul and Silas were praying and singing hymns to God, and the other prisoners were listening.', 'praise', 'NLT'),
('Psalm 150:1', 'Praise the LORD! Praise God in his sanctuary; praise him in his mighty heaven!', 'praise', 'NLT'),
('Psalm 146:1-2', 'Praise the LORD! Let all that I am praise the LORD. I will praise the LORD as long as I live. I will sing praises to my God with my dying breath.', 'praise', 'NLT'),

-- WISDOM (18 verses)
('Proverbs 3:5-6', 'Trust in the LORD with all your heart; do not depend on your own understanding. Seek his will in all you do, and he will show you which path to take.', 'wisdom', 'NLT'),
('James 1:5', 'If you need wisdom, ask our generous God, and he will give it to you. He will not rebuke you for asking.', 'wisdom', 'NLT'),
('Proverbs 4:7', 'Getting wisdom is the wisest thing you can do! And whatever else you do, develop good judgment.', 'wisdom', 'NLT'),
('Psalm 111:10', 'Fear of the LORD is the foundation of true wisdom. All who obey his commandments will grow in wisdom. Praise him forever!', 'wisdom', 'NLT'),
('Proverbs 2:6', 'For the LORD grants wisdom! From his mouth come knowledge and understanding.', 'wisdom', 'NLT'),
('Colossians 3:16', 'Let the message about Christ, in all its richness, fill your lives. Teach and counsel each other with all the wisdom he gives. Sing psalms and hymns and spiritual songs to God with thankful hearts.', 'wisdom', 'NLT'),
('Proverbs 16:16', 'How much better to get wisdom than gold, and good judgment than silver!', 'wisdom', 'NLT'),
('Ecclesiastes 7:12', 'Wisdom and money can get you almost anything, but only wisdom can save your life.', 'wisdom', 'NLT'),
('Proverbs 9:10', 'Fear of the LORD is the foundation of wisdom. Knowledge of the Holy One results in good judgment.', 'wisdom', 'NLT'),
('Proverbs 1:7', 'Fear of the LORD is the foundation of true knowledge, but fools despise wisdom and discipline.', 'wisdom', 'NLT'),
('Proverbs 19:20', 'Get all the advice and instruction you can, so you will be wise the rest of your life.', 'wisdom', 'NLT'),
('Proverbs 11:2', 'Pride leads to disgrace, but with humility comes wisdom.', 'wisdom', 'NLT'),
('Proverbs 3:13', 'Joyful is the person who finds wisdom, the one who gains understanding.', 'wisdom', 'NLT'),
('James 3:17', 'But the wisdom from above is first of all pure. It is also peace loving, gentle at all times, and willing to yield to others. It is full of mercy and the fruit of good deeds. It shows no favoritism and is always sincere.', 'wisdom', 'NLT'),
('Proverbs 24:14', 'In the same way, wisdom is sweet to your soul. If you find it, you will have a bright future, and your hopes will not be cut short.', 'wisdom', 'NLT'),
('Proverbs 12:15', 'Fools think their own way is right, but the wise listen to others.', 'wisdom', 'NLT'),
('Psalm 90:12', 'Teach us to realize the brevity of life, so that we may grow in wisdom.', 'wisdom', 'NLT'),
('1 Corinthians 1:30', 'God has united you with Christ Jesus. For our benefit God made him to be wisdom itself. Christ made us right with God; he made us pure and holy, and he freed us from sin.', 'wisdom', 'NLT'),

-- HOPE (19 verses)
('Romans 15:13', 'I pray that God, the source of hope, will fill you completely with joy and peace because you trust in him. Then you will overflow with confident hope through the power of the Holy Spirit.', 'hope', 'NLT'),
('Jeremiah 29:11', '"For I know the plans I have for you," says the LORD. "They are plans for good and not for disaster, to give you a future and a hope."', 'hope', 'NLT'),
('Romans 8:24-25', 'We were given this hope when we were saved. (If we already have something, we don''t need to hope for it. But if we look forward to something we don''t yet have, we must wait patiently and confidently.)', 'hope', 'NLT'),
('Psalm 62:5', 'Let all that I am wait quietly before God, for my hope is in him.', 'hope', 'NLT'),
('Hebrews 6:19', 'This hope is a strong and trustworthy anchor for our souls. It leads us through the curtain into God''s inner sanctuary.', 'hope', 'NLT'),
('Psalm 39:7', 'And so, Lord, where do I put my hope? My only hope is in you.', 'hope', 'NLT'),
('Psalm 71:5', 'O Lord, you alone are my hope. I''ve trusted you, O LORD, from childhood.', 'hope', 'NLT'),
('Romans 5:5', 'And this hope will not lead to disappointment. For we know how dearly God loves us, because he has given us the Holy Spirit to fill our hearts with his love.', 'hope', 'NLT'),
('1 Peter 1:3', 'All praise to God, the Father of our Lord Jesus Christ. It is by his great mercy that we have been born again, because God raised Jesus Christ from the dead. Now we live with great expectation.', 'hope', 'NLT'),
('Psalm 130:5', 'I am counting on the LORD; yes, I am counting on him. I have put my hope in his word.', 'hope', 'NLT'),
('Isaiah 40:31', 'But those who trust in the LORD will find new strength. They will soar high on wings like eagles. They will run and not grow weary. They will walk and not faint.', 'hope', 'NLT'),
('Romans 12:12', 'Rejoice in our confident hope. Be patient in trouble, and keep on praying.', 'hope', 'NLT'),
('Psalm 33:18', 'But the LORD watches over those who fear him, those who rely on his unfailing love.', 'hope', 'NLT'),
('Psalm 42:5', 'Why am I discouraged? Why is my heart so sad? I will put my hope in God! I will praise him again — my Savior and my God!', 'hope', 'NLT'),
('Psalm 146:5', 'But joyful are those who have the God of Israel as their helper, whose hope is in the LORD their God.', 'hope', 'NLT'),
('Titus 2:13', 'while we look forward with hope to that wonderful day when the glory of our great God and Savior, Jesus Christ, will be revealed.', 'hope', 'NLT'),
('Hebrews 11:1', 'Faith shows the reality of what we hope for; it is the evidence of things we cannot see.', 'hope', 'NLT'),
('Micah 7:7', 'As for me, I look to the LORD for help. I wait confidently for God to save me, and my God will certainly hear me.', 'hope', 'NLT'),
('Psalm 25:5', 'Lead me by your truth and teach me, for you are the God who saves me. All day long I put my hope in you.', 'hope', 'NLT'),

-- FAITH (18 verses)
('Hebrews 11:1', 'Faith shows the reality of what we hope for; it is the evidence of things we cannot see.', 'faith', 'NLT'),
('Romans 10:17', 'So faith comes from hearing, that is, hearing the Good News about Christ.', 'faith', 'NLT'),
('2 Corinthians 5:7', 'For we live by believing and not by seeing.', 'faith', 'NLT'),
('Matthew 17:20', '"You don''t have enough faith," Jesus told them. "I tell you the truth, if you had faith even as small as a mustard seed, you could say to this mountain, ''Move from here to there,'' and it would move. Nothing would be impossible."', 'faith', 'NLT'),
('Mark 11:24', 'I tell you, you can pray for anything, and if you believe that you''ve received it, it will be yours.', 'faith', 'NLT'),
('Ephesians 2:8-9', 'God saved you by his grace when you believed. And you can''t take credit for this; it is a gift from God. Salvation is not a reward for the good things we have done, so none of us can boast about it.', 'faith', 'NLT'),
('Galatians 2:20', 'My old self has been crucified with Christ. It is no longer I who live, but Christ lives in me. So I live in this earthly body by trusting in the Son of God, who loved me and gave himself for me.', 'faith', 'NLT'),
('James 2:17', 'So you see, faith by itself isn''t enough. Unless it produces good deeds, it is dead and useless.', 'faith', 'NLT'),
('1 John 5:4', 'For every child of God defeats this evil world, and we achieve this victory through our faith.', 'faith', 'NLT'),
('Romans 1:17', 'This Good News tells us how God makes us right in his sight. This is accomplished from start to finish by faith. As the Scriptures say, "It is through faith that a righteous person has life."', 'faith', 'NLT'),
('Mark 9:23', '"What do you mean, ''If I can''?'' Jesus asked. "Anything is possible if a person believes."', 'faith', 'NLT'),
('Hebrews 11:6', 'And it is impossible to please God without faith. Anyone who wants to come to him must believe that God exists and that he rewards those who sincerely seek him.', 'faith', 'NLT'),
('Romans 4:20-21', 'Abraham never wavered in believing God''s promise. In fact, his faith grew stronger, and in this he brought glory to God. He was fully convinced that God is able to do whatever he promises.', 'faith', 'NLT'),
('Matthew 21:22', 'You can pray for anything, and if you have faith, you will receive it.', 'faith', 'NLT'),
('1 Peter 1:7', 'These trials will show that your faith is genuine. It is being tested as fire tests and purifies gold — though your faith is far more precious than mere gold. So when your faith remains strong through many trials, it will bring you much praise and glory and honor on the day when Jesus Christ is revealed to the whole world.', 'faith', 'NLT'),
('Habakkuk 2:4', 'Look at the proud! They trust in themselves, and their lives are crooked. But the righteous will live by their faithfulness to God.', 'faith', 'NLT'),
('Luke 17:6', 'The Lord answered, "If you had faith even as small as a mustard seed, you could say to this mulberry tree, ''May you be uprooted and be planted in the sea,'' and it would obey you!"', 'faith', 'NLT'),
('Hebrews 12:2', 'We do this by keeping our eyes on Jesus, the champion who initiates and perfects our faith. Because of the joy awaiting him, he endured the cross, disregarding its shame. Now he is seated in the place of honor beside God''s throne.', 'faith', 'NLT'),

-- LOVE (19 verses)
('1 Corinthians 13:4-5', 'Love is patient and kind. Love is not jealous or boastful or proud or rude. It does not demand its own way. It is not irritable, and it keeps no record of being wronged.', 'love', 'NLT'),
('John 3:16', 'For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life.', 'love', 'NLT'),
('1 John 4:19', 'We love each other because he loved us first.', 'love', 'NLT'),
('Romans 8:38-39', 'And I am convinced that nothing can ever separate us from God''s love. Neither death nor life, neither angels nor demons, neither our fears for today nor our worries about tomorrow — not even the powers of hell can separate us from God''s love. No power in the sky above or in the earth below — indeed, nothing in all creation will ever be able to separate us from the love of God that is revealed in Christ Jesus our Lord.', 'love', 'NLT'),
('1 John 4:8', 'But anyone who does not love does not know God, for God is love.', 'love', 'NLT'),
('Jeremiah 31:3', 'Long ago the LORD said to Israel: "I have loved you, my people, with an everlasting love. With unfailing love I have drawn you to myself."', 'love', 'NLT'),
('1 Corinthians 13:13', 'Three things will last forever — faith, hope, and love — and the greatest of these is love.', 'love', 'NLT'),
('1 John 3:18', 'Dear children, let''s not merely say that we love each other; let us show the truth by our actions.', 'love', 'NLT'),
('John 15:13', 'There is no greater love than to lay down one''s life for one''s friends.', 'love', 'NLT'),
('Ephesians 3:17-19', 'Then Christ will make his home in your hearts as you trust in him. Your roots will grow down into God''s love and keep you strong. And may you have the power to understand, as all God''s people should, how wide, how long, how high, and how deep his love is. May you experience the love of Christ, though it is too great to understand fully. Then you will be made complete with all the fullness of life and power that comes from God.', 'love', 'NLT'),
('Deuteronomy 7:9', 'Understand, therefore, that the LORD your God is indeed God. He is the faithful God who keeps his covenant for a thousand generations and lavishes his unfailing love on those who love him and obey his commands.', 'love', 'NLT'),
('Psalm 36:7', 'How precious is your unfailing love, O God! All humanity finds shelter in the shadow of your wings.', 'love', 'NLT'),
('1 Peter 4:8', 'Most important of all, continue to show deep love for each other, for love covers a multitude of sins.', 'love', 'NLT'),
('Song of Solomon 8:7', 'Many waters cannot quench love, nor can rivers drown it. If a man tried to buy love with all his wealth, his offer would be utterly scorned.', 'love', 'NLT'),
('Romans 5:8', 'But God showed his great love for us by sending Christ to die for us while we were still sinners.', 'love', 'NLT'),
('Zephaniah 3:17', 'For the LORD your God is living among you. He is a mighty savior. He will take delight in you with gladness. With his love, he will calm all your fears. He will rejoice over you with joyful songs.', 'love', 'NLT'),
('Mark 12:30-31', 'And you must love the LORD your God with all your heart, all your soul, all your mind, and all your strength. The second is equally important: ''Love your neighbor as yourself.'' No other commandment is greater than these.', 'love', 'NLT'),
('John 13:34', 'So now I am giving you a new commandment: Love each other. Just as I have loved you, you should love each other.', 'love', 'NLT'),
('Psalm 86:15', 'But you, O Lord, are a God of compassion and mercy, slow to get angry and filled with unfailing love and faithfulness.', 'love', 'NLT'),

-- GUIDANCE (18 verses)
('Proverbs 3:5-6', 'Trust in the LORD with all your heart; do not depend on your own understanding. Seek his will in all you do, and he will show you which path to take.', 'guidance', 'NLT'),
('Psalm 32:8', 'The LORD says, "I will guide you along the best pathway for your life. I will advise you and watch over you."', 'guidance', 'NLT'),
('Psalm 119:105', 'Your word is a lamp to guide my feet and a light for my path.', 'guidance', 'NLT'),
('Isaiah 30:21', 'Your own ears will hear him. Right behind you a voice will say, "This is the way you should go," whether to the right or to the left.', 'guidance', 'NLT'),
('Psalm 37:23', 'The LORD directs the steps of the godly. He delights in every detail of their lives.', 'guidance', 'NLT'),
('Proverbs 16:9', 'We can make our plans, but the LORD determines our steps.', 'guidance', 'NLT'),
('Psalm 48:14', 'For that is what God is like. He is our God forever and ever, and he will guide us until we die.', 'guidance', 'NLT'),
('Isaiah 58:11', 'The LORD will guide you continually, giving you water when you are dry and restoring your strength. You will be like a well-watered garden, like an ever-flowing spring.', 'guidance', 'NLT'),
('John 16:13', 'When the Spirit of truth comes, he will guide you into all truth.', 'guidance', 'NLT'),
('Psalm 25:9', 'He leads the humble in doing right, teaching them his way.', 'guidance', 'NLT'),
('Proverbs 4:11', 'I will teach you wisdom''s ways and lead you in straight paths.', 'guidance', 'NLT'),
('Psalm 73:24', 'You guide me with your counsel, leading me to a glorious destiny.', 'guidance', 'NLT'),
('Psalm 143:10', 'Teach me to do your will, for you are my God. May your gracious Spirit lead me forward on a firm footing.', 'guidance', 'NLT'),
('Isaiah 42:16', 'I will lead blind Israel down a new path, guiding them along an unfamiliar way. I will brighten the darkness before them and smooth out the road ahead of them.', 'guidance', 'NLT'),
('Psalm 23:2-3', 'He lets me rest in green meadows; he leads me beside peaceful streams. He renews my strength. He guides me along right paths, bringing honor to his name.', 'guidance', 'NLT'),
('Proverbs 16:3', 'Commit your actions to the LORD, and your plans will succeed.', 'guidance', 'NLT'),
('Psalm 25:4-5', 'Show me the right path, O LORD; point out the road for me to follow. Lead me by your truth and teach me, for you are the God who saves me. All day long I put my hope in you.', 'guidance', 'NLT'),
('Romans 8:14', 'For all who are led by the Spirit of God are children of God.', 'guidance', 'NLT'),

-- GRATITUDE (18 verses)
('1 Thessalonians 5:18', 'Be thankful in all circumstances, for this is God''s will for you who belong to Christ Jesus.', 'gratitude', 'NLT'),
('Psalm 107:1', 'Give thanks to the LORD, for he is good! His faithful love endures forever.', 'gratitude', 'NLT'),
('Colossians 3:17', 'And whatever you do or say, do it as a representative of the Lord Jesus, giving thanks through him to God the Father.', 'gratitude', 'NLT'),
('Psalm 118:24', 'This is the day the LORD has made. We will rejoice and be glad in it.', 'gratitude', 'NLT'),
('Psalm 136:1', 'Give thanks to the LORD, for he is good! His faithful love endures forever.', 'gratitude', 'NLT'),
('Psalm 100:4-5', 'Enter his gates with thanksgiving; go into his courts with praise. Give thanks to him and praise his name. For the LORD is good. His unfailing love continues forever, and his faithfulness continues to each generation.', 'gratitude', 'NLT'),
('James 1:17', 'Whatever is good and perfect is a gift coming down to us from God our Father, who created all the lights in the heavens. He never changes or casts a shifting shadow.', 'gratitude', 'NLT'),
('Psalm 9:1', 'I will praise you, LORD, with all my heart; I will tell of all the marvelous things you have done.', 'gratitude', 'NLT'),
('Ephesians 5:20', 'And give thanks for everything to God the Father in the name of our Lord Jesus Christ.', 'gratitude', 'NLT'),
('Psalm 106:1', 'Praise the LORD! Give thanks to the LORD, for he is good! His faithful love endures forever.', 'gratitude', 'NLT'),
('Philippians 4:6', 'Don''t worry about anything; instead, pray about everything. Tell God what you need, and thank him for all he has done.', 'gratitude', 'NLT'),
('Psalm 50:14', 'Make thankfulness your sacrifice to God, and keep the vows you made to the Most High.', 'gratitude', 'NLT'),
('1 Chronicles 16:34', 'Give thanks to the LORD, for he is good! His faithful love endures forever.', 'gratitude', 'NLT'),
('Psalm 69:30', 'Then I will praise God''s name with singing, and I will honor him with thanksgiving.', 'gratitude', 'NLT'),
('Colossians 2:7', 'Let your roots grow down into him, and let your lives be built on him. Then your faith will grow strong in the truth you were taught, and you will overflow with thankfulness.', 'gratitude', 'NLT'),
('Daniel 2:23', 'I thank and praise you, God of my ancestors, for you have given me wisdom and strength. You have told me what we asked of you and revealed to us what the king demanded.', 'gratitude', 'NLT'),
('Psalm 75:1', 'We thank you, O God! We give thanks because you are near. People everywhere tell of your wonderful deeds.', 'gratitude', 'NLT'),
('2 Corinthians 9:15', 'Thank God for this gift too wonderful for words!', 'gratitude', 'NLT'),

-- COURAGE (18 verses)
('Joshua 1:9', 'This is my command — be strong and courageous! Do not be afraid or discouraged. For the LORD your God is with you wherever you go.', 'courage', 'NLT'),
('Deuteronomy 31:6', 'So be strong and courageous! Do not be afraid and do not panic before them. For the LORD your God will personally go ahead of you. He will neither fail you nor abandon you.', 'courage', 'NLT'),
('Isaiah 41:10', 'Don''t be afraid, for I am with you. Don''t be discouraged, for I am your God. I will strengthen you and help you. I will hold you up with my victorious right hand.', 'courage', 'NLT'),
('Psalm 27:14', 'Wait patiently for the LORD. Be brave and courageous. Yes, wait patiently for the LORD.', 'courage', 'NLT'),
('2 Timothy 1:7', 'For God has not given us a spirit of fear and timidity, but of power, love, and self-discipline.', 'courage', 'NLT'),
('Psalm 56:3', 'But when I am afraid, I will put my trust in you.', 'courage', 'NLT'),
('Isaiah 43:1', 'But now, O Jacob, listen to the LORD who created you. O Israel, the one who formed you says, "Do not be afraid, for I have ransomed you. I have called you by name; you are mine."', 'courage', 'NLT'),
('Psalm 118:6', 'The LORD is for me, so I will have no fear. What can mere people do to me?', 'courage', 'NLT'),
('Romans 8:31', 'What shall we say about such wonderful things as these? If God is for us, who can ever be against us?', 'courage', 'NLT'),
('1 Chronicles 28:20', 'Then David continued, "Be strong and courageous, and do the work. Don''t be afraid or discouraged, for the LORD God, my God, is with you. He will not fail you or forsake you."', 'courage', 'NLT'),
('Psalm 31:24', 'So be strong and courageous, all you who put your hope in the LORD!', 'courage', 'NLT'),
('Proverbs 28:1', 'The wicked run away when no one is chasing them, but the godly are as bold as lions.', 'courage', 'NLT'),
('Psalm 112:7', 'They do not fear bad news; they confidently trust the LORD to care for them.', 'courage', 'NLT'),
('Isaiah 35:4', 'Say to those with fearful hearts, "Be strong, and do not fear, for your God is coming to destroy your enemies. He is coming to save you."', 'courage', 'NLT'),
('Acts 4:31', 'After this prayer, the meeting place shook, and they were all filled with the Holy Spirit. Then they preached the word of God with boldness.', 'courage', 'NLT'),
('Psalm 23:4', 'Even when I walk through the darkest valley, I will not be afraid, for you are close beside me. Your rod and your staff protect and comfort me.', 'courage', 'NLT'),
('John 14:27', 'I am leaving you with a gift — peace of mind and heart. And the peace I give is a gift the world cannot give. So don''t be troubled or afraid.', 'courage', 'NLT'),
('Hebrews 13:6', 'So we can say with confidence, "The LORD is my helper, so I will have no fear. What can mere people do to me?"', 'courage', 'NLT'),

-- PATIENCE (18 verses)
('James 1:2-4', 'Dear brothers and sisters, when troubles of any kind come your way, consider it an opportunity for great joy. For you know that when your faith is tested, your endurance has a chance to grow. So let it grow, for when your endurance is fully developed, you will be perfect and complete, needing nothing.', 'patience', 'NLT'),
('Romans 12:12', 'Rejoice in our confident hope. Be patient in trouble, and keep on praying.', 'patience', 'NLT'),
('Ecclesiastes 7:8', 'Finishing is better than starting. Patience is better than pride.', 'patience', 'NLT'),
('Galatians 6:9', 'So let''s not get tired of doing what is good. At just the right time we will reap a harvest of blessing if we don''t give up.', 'patience', 'NLT'),
('Psalm 37:7', 'Be still in the presence of the LORD, and wait patiently for him to act. Don''t worry about evil people who prosper or fret about their wicked schemes.', 'patience', 'NLT'),
('Hebrews 10:36', 'Patient endurance is what you need now, so that you will continue to do God''s will. Then you will receive all that he has promised.', 'patience', 'NLT'),
('Isaiah 40:31', 'But those who trust in the LORD will find new strength. They will soar high on wings like eagles. They will run and not grow weary. They will walk and not faint.', 'patience', 'NLT'),
('Psalm 40:1', 'I waited patiently for the LORD to help me, and he turned to me and heard my cry.', 'patience', 'NLT'),
('Romans 8:25', 'But if we look forward to something we don''t yet have, we must wait patiently and confidently.', 'patience', 'NLT'),
('Colossians 1:11', 'We also pray that you will be strengthened with all his glorious power so you will have all the endurance and patience you need. May you be filled with joy.', 'patience', 'NLT'),
('Proverbs 14:29', 'People with understanding control their anger; a hot temper shows great foolishness.', 'patience', 'NLT'),
('2 Peter 3:9', 'The Lord isn''t really being slow about his promise, as some people think. No, he is being patient for your sake. He does not want anyone to be destroyed, but wants everyone to repent.', 'patience', 'NLT'),
('Lamentations 3:25', 'The LORD is good to those who depend on him, to those who search for him.', 'patience', 'NLT'),
('Proverbs 15:18', 'A hot-tempered person starts fights; a cool-tempered person stops them.', 'patience', 'NLT'),
('1 Corinthians 13:4', 'Love is patient and kind. Love is not jealous or boastful or proud.', 'patience', 'NLT'),
('Psalm 27:14', 'Wait patiently for the LORD. Be brave and courageous. Yes, wait patiently for the LORD.', 'patience', 'NLT'),
('Habakkuk 2:3', 'This vision is for a future time. It describes the end, and it will be fulfilled. If it seems slow in coming, wait patiently, for it will surely take place. It will not be delayed.', 'patience', 'NLT'),
('James 5:7-8', 'Dear brothers and sisters, be patient as you wait for the Lord''s return. Consider the farmers who patiently wait for the rains in the fall and in the spring. They eagerly look for the valuable harvest to ripen. You, too, must be patient. Take courage, for the coming of the Lord is near.', 'patience', 'NLT'),

-- JOY (18 verses)
('Nehemiah 8:10', 'And Nehemiah continued, "Go and celebrate with a feast of rich foods and sweet drinks, and share gifts of food with people who have nothing prepared. This is a sacred day before our Lord. Don''t be dejected and sad, for the joy of the LORD is your strength!"', 'joy', 'NLT'),
('Psalm 16:11', 'You will show me the way of life, granting me the joy of your presence and the pleasures of living with you forever.', 'joy', 'NLT'),
('John 15:11', 'I have told you these things so that you will be filled with my joy. Yes, your joy will overflow!', 'joy', 'NLT'),
('Psalm 30:5', 'For his anger lasts only a moment, but his favor lasts a lifetime! Weeping may last through the night, but joy comes with the morning.', 'joy', 'NLT'),
('Romans 15:13', 'I pray that God, the source of hope, will fill you completely with joy and peace because you trust in him. Then you will overflow with confident hope through the power of the Holy Spirit.', 'joy', 'NLT'),
('Philippians 4:4', 'Always be full of joy in the Lord. I say it again — rejoice!', 'joy', 'NLT'),
('James 1:2', 'Dear brothers and sisters, when troubles of any kind come your way, consider it an opportunity for great joy.', 'joy', 'NLT'),
('Psalm 126:5', 'Those who plant in tears will harvest with shouts of joy.', 'joy', 'NLT'),
('Psalm 5:11', 'But let all who take refuge in you rejoice; let them sing joyful praises forever. Spread your protection over them, that all who love your name may be filled with joy.', 'joy', 'NLT'),
('Isaiah 61:10', 'I am overwhelmed with joy in the LORD my God! For he has dressed me with the clothing of salvation and draped me in a robe of righteousness.', 'joy', 'NLT'),
('1 Peter 1:8', 'You love him even though you have never seen him. Though you do not see him now, you trust him; and you rejoice with a glorious, inexpressible joy.', 'joy', 'NLT'),
('Psalm 98:4', 'Shout to the LORD, all the earth; break out in praise and sing for joy!', 'joy', 'NLT'),
('Psalm 47:1', 'Come, everyone! Clap your hands! Shout to God with joyful praise!', 'joy', 'NLT'),
('Psalm 118:24', 'This is the day the LORD has made. We will rejoice and be glad in it.', 'joy', 'NLT'),
('Habakkuk 3:18', 'Yet I will rejoice in the LORD! I will be joyful in the God of my salvation!', 'joy', 'NLT'),
('Zephaniah 3:17', 'For the LORD your God is living among you. He is a mighty savior. He will take delight in you with gladness. With his love, he will calm all your fears. He will rejoice over you with joyful songs.', 'joy', 'NLT'),
('Galatians 5:22', 'But the Holy Spirit produces this kind of fruit in our lives: love, joy, peace, patience, kindness, goodness, faithfulness.', 'joy', 'NLT'),
('John 16:22', 'So you have sorrow now, but I will see you again; then you will rejoice, and no one can rob you of that joy.', 'joy', 'NLT'),

-- TRUST (18 verses)
('Proverbs 3:5', 'Trust in the LORD with all your heart; do not depend on your own understanding.', 'trust', 'NLT'),
('Psalm 56:3-4', 'But when I am afraid, I will put my trust in you. I praise God for what he has promised. I trust in God, so why should I be afraid? What can mere mortals do to me?', 'trust', 'NLT'),
('Psalm 37:5', 'Commit everything you do to the LORD. Trust him, and he will help you.', 'trust', 'NLT'),
('Psalm 9:10', 'Those who know your name trust in you, for you, O LORD, do not abandon those who search for you.', 'trust', 'NLT'),
('Psalm 62:8', 'O my people, trust in him at all times. Pour out your heart to him, for God is our refuge.', 'trust', 'NLT'),
('Psalm 20:7', 'Some nations boast of their chariots and horses, but we boast in the name of the LORD our God.', 'trust', 'NLT'),
('Psalm 115:11', 'All you who fear the LORD, trust the LORD! He is your helper and your shield.', 'trust', 'NLT'),
('Nahum 1:7', 'The LORD is good, a strong refuge when trouble comes. He is close to those who trust in him.', 'trust', 'NLT'),
('Psalm 125:1', 'Those who trust in the LORD are as secure as Mount Zion; they will not be defeated but will endure forever.', 'trust', 'NLT'),
('Psalm 91:2', 'This I declare about the LORD: He alone is my refuge, my place of safety; he is my God, and I trust him.', 'trust', 'NLT'),
('Psalm 37:3', 'Trust in the LORD and do good. Then you will live safely in the land and prosper.', 'trust', 'NLT'),
('Isaiah 12:2', 'See, God has come to save me. I will trust in him and not be afraid. The LORD GOD is my strength and my song; he has given me victory.', 'trust', 'NLT'),
('Psalm 5:11', 'But let all who take refuge in you rejoice; let them sing joyful praises forever. Spread your protection over them, that all who love your name may be filled with joy.', 'trust', 'NLT'),
('Psalm 28:7', 'The LORD is my strength and shield. I trust him with all my heart. He helps me, and my heart is filled with joy.', 'trust', 'NLT'),
('Psalm 40:4', 'Oh, the joys of those who trust the LORD, who have no confidence in the proud or in those who worship idols.', 'trust', 'NLT'),
('Psalm 84:12', 'O LORD of Heaven''s Armies, what joy for those who trust in you.', 'trust', 'NLT'),
('Psalm 143:8', 'Let me hear of your unfailing love each morning, for I am trusting you. Show me where to walk, for I give myself to you.', 'trust', 'NLT'),
('Jeremiah 17:7', 'But blessed are those who trust in the LORD and have made the LORD their hope and confidence.', 'trust', 'NLT'),

-- PROVISION (18 verses)
('Philippians 4:19', 'And this same God who takes care of me will supply all your needs from his glorious riches, which have been given to us in Christ Jesus.', 'provision', 'NLT'),
('Matthew 6:33', 'Seek the Kingdom of God above all else, and live righteously, and he will give you everything you need.', 'provision', 'NLT'),
('Psalm 23:1', 'The LORD is my shepherd; I have all that I need.', 'provision', 'NLT'),
('Psalm 37:25', 'Once I was young, and now I am old. Yet I have never seen the godly abandoned or their children begging for bread.', 'provision', 'NLT'),
('Deuteronomy 8:18', 'Remember the LORD your God. He is the one who gives you power to be successful, in order to fulfill the covenant he confirmed to your ancestors with an oath.', 'provision', 'NLT'),
('Luke 12:24', 'Look at the ravens. They don''t plant or harvest or store food in barns, for God feeds them. And you are far more valuable to him than any birds!', 'provision', 'NLT'),
('Matthew 6:26', 'Look at the birds. They don''t plant or harvest or store food in barns, for your heavenly Father feeds them. And aren''t you far more valuable to him than they are?', 'provision', 'NLT'),
('Psalm 34:10', 'Even strong young lions sometimes go hungry, but those who trust in the LORD will lack no good thing.', 'provision', 'NLT'),
('Psalm 145:15-16', 'The eyes of all look to you in hope; you give them their food as they need it. When you open your hand, you satisfy the hunger and thirst of every living thing.', 'provision', 'NLT'),
('Genesis 22:14', 'Abraham named the place Yahweh-Yireh (which means "the LORD will provide"). To this day, people still use that name as a proverb: "On the mountain of the LORD it will be provided."', 'provision', 'NLT'),
('2 Corinthians 9:8', 'And God will generously provide all you need. Then you will always have everything you need and plenty left over to share with others.', 'provision', 'NLT'),
('Psalm 111:5', 'He gives food to those who fear him; he always remembers his covenant.', 'provision', 'NLT'),
('Psalm 132:15', 'I will bless this city and make it prosperous; I will satisfy its poor with food.', 'provision', 'NLT'),
('Joel 2:26', 'Once again you will have all the food you want, and you will praise the LORD your God, who does these miracles for you. Never again will my people be disgraced.', 'provision', 'NLT'),
('Proverbs 10:3', 'The LORD will not let the godly go hungry, but he refuses to satisfy the craving of the wicked.', 'provision', 'NLT'),
('Isaiah 58:11', 'The LORD will guide you continually, giving you water when you are dry and restoring your strength. You will be like a well-watered garden, like an ever-flowing spring.', 'provision', 'NLT'),
('Malachi 3:10', '"Bring all the tithes into the storehouse so there will be enough food in my Temple. If you do," says the LORD of Heaven''s Armies, "I will open the windows of heaven for you. I will pour out a blessing so great you won''t have enough room to take it in!"', 'provision', 'NLT'),
('Psalm 68:19', 'Praise the Lord; praise God our savior! For each day he carries us in his arms.', 'provision', 'NLT'),

-- PROTECTION (18 verses)
('Psalm 91:1-2', 'Those who live in the shelter of the Most High will find rest in the shadow of the Almighty. This I declare about the LORD: He alone is my refuge, my place of safety; he is my God, and I trust him.', 'protection', 'NLT'),
('Psalm 121:7-8', 'The LORD keeps you from all harm and watches over your life. The LORD keeps watch over you as you come and go, both now and forever.', 'protection', 'NLT'),
('Psalm 34:7', 'For the angel of the LORD is a guard; he surrounds and defends all who fear him.', 'protection', 'NLT'),
('Psalm 18:2', 'The LORD is my rock, my fortress, and my savior; my God is my rock, in whom I find protection. He is my shield, the power that saves me, and my place of safety.', 'protection', 'NLT'),
('Psalm 91:11', 'For he will order his angels to protect you wherever you go.', 'protection', 'NLT'),
('2 Thessalonians 3:3', 'But the Lord is faithful; he will strengthen you and guard you from the evil one.', 'protection', 'NLT'),
('Psalm 32:7', 'For you are my hiding place; you protect me from trouble. You surround me with songs of victory.', 'protection', 'NLT'),
('Proverbs 18:10', 'The name of the LORD is a strong fortress; the godly run to him and are safe.', 'protection', 'NLT'),
('Psalm 46:1', 'God is our refuge and strength, always ready to help in times of trouble.', 'protection', 'NLT'),
('Isaiah 54:17', 'But in that coming day no weapon turned against you will succeed. You will silence every voice raised up to accuse you. These benefits are enjoyed by the servants of the LORD; their vindication will come from me. I, the LORD, have spoken!', 'protection', 'NLT'),
('Psalm 121:3-4', 'He will not let you stumble; the one who watches over you will not slumber. Indeed, he who watches over Israel never slumbers or sleeps.', 'protection', 'NLT'),
('Psalm 91:4', 'He will cover you with his feathers. He will shelter you with his wings. His faithful promises are your armor and protection.', 'protection', 'NLT'),
('Psalm 59:16', 'But as for me, I will sing about your power. Each morning I will sing with joy about your unfailing love. For you have been my refuge, a place of safety when I am in distress.', 'protection', 'NLT'),
('Psalm 144:2', 'He is my loving ally and my fortress, my tower of safety, my rescuer. He is my shield, and I take refuge in him.', 'protection', 'NLT'),
('Psalm 3:3', 'But you, O LORD, are a shield around me; you are my glory, the one who holds my head high.', 'protection', 'NLT'),
('Deuteronomy 33:27', 'The eternal God is your refuge, and his everlasting arms are under you.', 'protection', 'NLT'),
('Psalm 61:3', 'For you are my safe refuge, a fortress where my enemies cannot reach me.', 'protection', 'NLT'),
('2 Samuel 22:3', 'My God is my rock, in whom I find protection. He is my shield, the power that saves me, and my place of safety. He is my refuge, my savior, the one who saves me from violence.', 'protection', 'NLT'),

-- HEALING (18 verses)
('Psalm 103:2-3', 'Let all that I am praise the LORD; may I never forget the good things he does for me. He forgives all my sins and heals all my diseases.', 'healing', 'NLT'),
('Jeremiah 17:14', 'O LORD, if you heal me, I will be truly healed; if you save me, I will be truly saved. My praises are for you alone!', 'healing', 'NLT'),
('James 5:15', 'Such a prayer offered in faith will heal the sick, and the Lord will make you well. And if you have committed any sins, you will be forgiven.', 'healing', 'NLT'),
('Isaiah 53:5', 'But he was pierced for our rebellion, crushed for our sins. He was beaten so we could be whole. He was whipped so we could be healed.', 'healing', 'NLT'),
('Exodus 15:26', 'He said, "If you will listen carefully to the voice of the LORD your God and do what is right in his sight, obeying his commands and keeping all his decrees, then I will not make you suffer any of the diseases I sent on the Egyptians; for I am the LORD who heals you."', 'healing', 'NLT'),
('Psalm 147:3', 'He heals the brokenhearted and bandages their wounds.', 'healing', 'NLT'),
('3 John 1:2', 'Dear friend, I hope all is well with you and that you are as healthy in body as you are strong in spirit.', 'healing', 'NLT'),
('Proverbs 17:22', 'A cheerful heart is good medicine, but a broken spirit saps a person''s strength.', 'healing', 'NLT'),
('Psalm 41:3', 'The LORD nurses them when they are sick and restores them to health.', 'healing', 'NLT'),
('Matthew 9:35', 'Jesus traveled through all the towns and villages of that area, teaching in the synagogues and announcing the Good News about the Kingdom. And he healed every kind of disease and illness.', 'healing', 'NLT'),
('Isaiah 57:18', 'I have seen what they do, but I will heal them anyway! I will lead them. I will comfort those who mourn.', 'healing', 'NLT'),
('Malachi 4:2', 'But for you who fear my name, the Sun of Righteousness will rise with healing in his wings. And you will go free, leaping with joy like calves let out to pasture.', 'healing', 'NLT'),
('Psalm 30:2', 'O LORD my God, I cried to you for help, and you restored my health.', 'healing', 'NLT'),
('Proverbs 4:20-22', 'My child, pay attention to what I say. Listen carefully to my words. Don''t lose sight of them. Let them penetrate deep into your heart, for they bring life to those who find them, and healing to their whole body.', 'healing', 'NLT'),
('James 5:16', 'Confess your sins to each other and pray for each other so that you may be healed. The earnest prayer of a righteous person has great power and produces wonderful results.', 'healing', 'NLT'),
('Hosea 6:1', '"Come, let us return to the LORD. He has torn us to pieces; now he will heal us. He has injured us; now he will bandage our wounds."', 'healing', 'NLT'),
('Psalm 107:20', 'He sent out his word and healed them, snatching them from the door of death.', 'healing', 'NLT'),
('Isaiah 38:16', 'Lord, your discipline is good, for it leads to life and health. You restore my health and allow me to live!', 'healing', 'NLT'),

-- FORGIVENESS (18 verses)
('1 John 1:9', 'But if we confess our sins to him, he is faithful and just to forgive us our sins and to cleanse us from all wickedness.', 'forgiveness', 'NLT'),
('Ephesians 4:32', 'Instead, be kind to each other, tenderhearted, forgiving one another, just as God through Christ has forgiven you.', 'forgiveness', 'NLT'),
('Psalm 103:12', 'He has removed our sins as far from us as the east is from the west.', 'forgiveness', 'NLT'),
('Colossians 3:13', 'Make allowance for each other''s faults, and forgive anyone who offends you. Remember, the Lord forgave you, so you must forgive others.', 'forgiveness', 'NLT'),
('Isaiah 1:18', '"Come now, let''s settle this," says the LORD. "Though your sins are like scarlet, I will make them as white as snow. Though they are red like crimson, I will make them as white as wool."', 'forgiveness', 'NLT'),
('Micah 7:18-19', 'Where is another God like you, who pardons the guilt of the remnant, overlooking the sins of his special people? You will not stay angry with your people forever, because you delight in showing unfailing love. Once again you will have compassion on us. You will trample our sins under your feet and throw them into the depths of the ocean!', 'forgiveness', 'NLT'),
('Psalm 32:1', 'Oh, what joy for those whose disobedience is forgiven, whose sin is put out of sight!', 'forgiveness', 'NLT'),
('Acts 3:19', 'Now repent of your sins and turn to God, so that your sins may be wiped away.', 'forgiveness', 'NLT'),
('Matthew 6:14', 'If you forgive those who sin against you, your heavenly Father will forgive you.', 'forgiveness', 'NLT'),
('Romans 8:1', 'So now there is no condemnation for those who belong to Christ Jesus.', 'forgiveness', 'NLT'),
('2 Chronicles 7:14', 'Then if my people who are called by my name will humble themselves and pray and seek my face and turn from their wicked ways, I will hear from heaven and will forgive their sins and restore their land.', 'forgiveness', 'NLT'),
('Psalm 86:5', 'O Lord, you are so good, so ready to forgive, so full of unfailing love for all who ask for your help.', 'forgiveness', 'NLT'),
('Isaiah 43:25', 'I — yes, I alone — will blot out your sins for my own sake and will never think of them again.', 'forgiveness', 'NLT'),
('Hebrews 8:12', 'And I will forgive their wickedness, and I will never again remember their sins.', 'forgiveness', 'NLT'),
('Luke 6:37', 'Do not judge others, and you will not be judged. Do not condemn others, or it will all come back against you. Forgive others, and you will be forgiven.', 'forgiveness', 'NLT'),
('Psalm 130:3-4', 'LORD, if you kept a record of our sins, who, O Lord, could ever survive? But you offer forgiveness, that we might learn to fear you.', 'forgiveness', 'NLT'),
('Matthew 18:21-22', 'Then Peter came to him and asked, "Lord, how often should I forgive someone who sins against me? Seven times?" "No, not seven times," Jesus replied, "but seventy times seven!"', 'forgiveness', 'NLT'),
('Jeremiah 31:34', 'And they will not need to teach their neighbors, nor will they need to teach their relatives, saying, ''You should know the LORD.'' For everyone, from the least to the greatest, will know me already," says the LORD. "And I will forgive their wickedness, and I will never again remember their sins."', 'forgiveness', 'NLT'),

-- PURPOSE (19 verses)
('Jeremiah 29:11', '"For I know the plans I have for you," says the LORD. "They are plans for good and not for disaster, to give you a future and a hope."', 'purpose', 'NLT'),
('Romans 8:28', 'And we know that God causes everything to work together for the good of those who love God and are called according to his purpose for them.', 'purpose', 'NLT'),
('Ephesians 2:10', 'For we are God''s masterpiece. He has created us anew in Christ Jesus, so we can do the good things he planned for us long ago.', 'purpose', 'NLT'),
('Proverbs 19:21', 'You can make many plans, but the LORD''s purpose will prevail.', 'purpose', 'NLT'),
('Psalm 138:8', 'The LORD will work out his plans for my life — for your faithful love, O LORD, endures forever. Don''t abandon me, for you made me.', 'purpose', 'NLT'),
('Philippians 2:13', 'For God is working in you, giving you the desire and the power to do what pleases him.', 'purpose', 'NLT'),
('Isaiah 46:10', 'Only I can tell you the future before it even happens. Everything I plan will come to pass, for I do whatever I wish.', 'purpose', 'NLT'),
('Proverbs 16:4', 'The LORD has made everything for his own purposes, even the wicked for a day of disaster.', 'purpose', 'NLT'),
('Colossians 1:16', 'For through him God created everything in the heavenly realms and on earth. He made the things we can see and the things we can''t see — such as thrones, kingdoms, rulers, and authorities in the unseen world. Everything was created through him and for him.', 'purpose', 'NLT'),
('Psalm 57:2', 'I cry out to God Most High, to God who will fulfill his purpose for me.', 'purpose', 'NLT'),
('Isaiah 14:27', 'The LORD of Heaven''s Armies has spoken — who can change his plans? When his hand is raised, who can stop him?', 'purpose', 'NLT'),
('Psalm 33:11', 'But the LORD''s plans stand firm forever; his intentions can never be shaken.', 'purpose', 'NLT'),
('Romans 12:2', 'Don''t copy the behavior and customs of this world, but let God transform you into a new person by changing the way you think. Then you will learn to know God''s will for you, which is good and pleasing and perfect.', 'purpose', 'NLT'),
('Ecclesiastes 3:1', 'For everything there is a season, a time for every activity under heaven.', 'purpose', 'NLT'),
('2 Timothy 1:9', 'For God saved us and called us to live a holy life. He did this, not because we deserved it, but because that was his plan from before the beginning of time — to show us his grace through Christ Jesus.', 'purpose', 'NLT'),
('1 Peter 2:9', 'But you are not like that, for you are a chosen people. You are royal priests, a holy nation, God''s very own possession. As a result, you can show others the goodness of God, for he called you out of the darkness into his wonderful light.', 'purpose', 'NLT'),
('Esther 4:14', 'If you keep quiet at a time like this, deliverance and relief for the Jews will arise from some other place, but you and your relatives will die. Who knows if perhaps you were made queen for just such a time as this?', 'purpose', 'NLT'),
('Proverbs 16:9', 'We can make our plans, but the LORD determines our steps.', 'purpose', 'NLT'),
('Matthew 5:16', 'In the same way, let your good deeds shine out for all to see, so that everyone will praise your heavenly Father.', 'purpose', 'NLT'),

-- PRAYER (19 verses)
('Matthew 7:7', 'Keep on asking, and you will receive what you ask for. Keep on seeking, and you will find. Keep on knocking, and the door will be opened to you.', 'prayer', 'NLT'),
('Philippians 4:6', 'Don''t worry about anything; instead, pray about everything. Tell God what you need, and thank him for all he has done.', 'prayer', 'NLT'),
('1 Thessalonians 5:17', 'Never stop praying.', 'prayer', 'NLT'),
('Jeremiah 33:3', '"Ask me and I will tell you remarkable secrets you do not know about things to come."', 'prayer', 'NLT'),
('James 5:16', 'Confess your sins to each other and pray for each other so that you may be healed. The earnest prayer of a righteous person has great power and produces wonderful results.', 'prayer', 'NLT'),
('Psalm 145:18', 'The LORD is close to all who call on him, yes, to all who call on him in truth.', 'prayer', 'NLT'),
('1 John 5:14', 'And we are confident that he hears us whenever we ask for anything that pleases him.', 'prayer', 'NLT'),
('Matthew 6:6', 'But when you pray, go away by yourself, shut the door behind you, and pray to your Father in private. Then your Father, who sees everything, will reward you.', 'prayer', 'NLT'),
('Mark 11:24', 'I tell you, you can pray for anything, and if you believe that you''ve received it, it will be yours.', 'prayer', 'NLT'),
('Psalm 34:17', 'The LORD hears his people when they call to him for help. He rescues them from all their troubles.', 'prayer', 'NLT'),
('Romans 8:26', 'And the Holy Spirit helps us in our weakness. For example, we don''t know what God wants us to pray for. But the Holy Spirit prays for us with groanings that cannot be expressed in words.', 'prayer', 'NLT'),
('2 Chronicles 7:14', 'Then if my people who are called by my name will humble themselves and pray and seek my face and turn from their wicked ways, I will hear from heaven and will forgive their sins and restore their land.', 'prayer', 'NLT'),
('Psalm 65:2', 'O God, you answer our prayers, and to you all people will come.', 'prayer', 'NLT'),
('Isaiah 65:24', 'I will answer them before they even call to me. While they are still talking about their needs, I will go ahead and answer their prayers!', 'prayer', 'NLT'),
('John 15:7', 'But if you remain in me and my words remain in you, you may ask for anything you want, and it will be granted!', 'prayer', 'NLT'),
('Psalm 91:15', 'When they call on me, I will answer; I will be with them in trouble. I will rescue and honor them.', 'prayer', 'NLT'),
('Hebrews 4:16', 'So let us come boldly to the throne of our gracious God. There we will receive his mercy, and we will find grace to help us when we need it most.', 'prayer', 'NLT'),
('Luke 11:9', 'And so I tell you, keep on asking, and you will receive what you ask for. Keep on seeking, and you will find. Keep on knocking, and the door will be opened to you.', 'prayer', 'NLT'),
('Psalm 17:6', 'I am praying to you because I know you will answer, O God. Bend down and listen as I pray.', 'prayer', 'NLT');
